"""Simplified Chinese interface labels and PKHeX species names.

Species source: https://github.com/kwsch/PKHeX/tree/master/PKHeX.Core/Resources/text/other
"""

LABELS = {'Games': '游戏',
 'Board': '开发板',
 'Boards': '开发板',
 'Docs': '文档',
 'Documentation': '文档',
 'Settings': '设置',
 'Update': '更新',
 'Updates': '更新',
 'Loading': '加载中',
 'Loading...': '加载中…',
 'Loading species': '正在加载种类',
 'Loading species...': '正在加载种类…',
 'Loading names': '正在加载名称',
 'Loading options': '正在加载选项',
 'Loading sprite': '正在加载图像',
 'Species': '种类',
 'Level': '等级',
 'Shiny': '异色',
 'Nature': '性格',
 'Form': '形态',
 'Ability': '特性',
 'Gender': '性别',
 'Ball': '精灵球',
 'Held item': '携带道具',
 'IVs': '个体值',
 'EVs': '努力值',
 'AVs': '觉醒值',
 'Effort levels': '奋斗等级',
 'Atk': '攻击',
 'Def': '防御',
 'SpA': '特攻',
 'SpD': '特防',
 'Spe': '速度',
 'Male': '雄性',
 'Female': '雌性',
 'Build': '生成',
 'Apply': '应用',
 'Cancel': '取消',
 'Clear': '清除',
 'Copy': '复制',
 'Search': '搜索',
 'Random': '随机',
 'Any': '任意',
 'random': '随机',
 'auto': '自动',
 'Not set': '未设置',
 'Legal': '合法',
 'Not legal': '不合法',
 'Unavailable': '不可用',
 'Nickname': '昵称',
 'Nickname (optional)': '昵称（可选）',
 'Search a species': '搜索种类',
 'Pick a species first.': '请先选择种类。',
 'Finding a legal encounter...': '正在寻找合法的遭遇…',
 'Building Pokemon': '正在生成宝可梦',
 'Or use a Pokemon file': '或使用宝可梦文件',
 'Import paste': '导入文本',
 'or drop either here': '也可将文件拖放到此处',
 'Paste a set first.': '请先粘贴配置。',
 'Reading the set': '正在读取配置',
 'Reading the set...': '正在读取配置…',
 'Import a Showdown set': '导入 Showdown 配置',
 'Paste a set exported from Pokemon Showdown, Smogon or PKHeX. Its values fill the form; press Build to make a legal Pokemon from them.': '粘贴从 '
                                                                                                                                          'Pokémon '
                                                                                                                                          'Showdown、Smogon '
                                                                                                                                          '或 '
                                                                                                                                          'PKHeX '
                                                                                                                                          '导出的配置。导入后点击“生成”，即可按配置生成合法的宝可梦。',
 'More options': '更多选项',
 'Reading what this species can have...': '正在读取该种类可用的选项…',
 "Empty means random. The build is checked by PKHeX's legality analysis.": '留空表示随机。生成结果将通过 PKHeX 的合法性分析。',
 "Moves (empty means the encounter's own)": '招式（留空使用该遭遇的原有招式）',
 'Add a trade': '添加交换',
 'Remove this trade': '移除此交换',
 'Pikachu': '皮卡丘',
 'Eevee': '伊布',
 'Bulbasaur': '妙蛙种子',
 'Charmander': '小火龙',
 'Squirtle': '杰尼龟',
 'Pidgey': '波波',
 'Caterpie': '绿毛虫',
 'Rattata': '小拉达',
 'Jigglypuff': '胖丁',
 'Diglett': '地鼠',
 'Trade': '交换',
 'Mystery Gift': '神秘礼物',
 'Trade (Host)': '交换（主机）',
 'Trade (Join)': '交换（加入）',
 'Your console joins pokeldn': '游戏机加入 pokeldn',
 'pokeldn joins your console': 'pokeldn 加入游戏机',
 'Basic': '基本',
 'Advanced': '高级',
 'Advanced options': '高级选项',
 'Search the options': '搜索选项',
 'No option matches.': '没有匹配的选项。',
 'This tool takes no options beyond its Basic fields.': '此功能没有额外的高级选项。',
 'The tested defaults work for most players. Change these only when a guide or a bug report asks you to. A value set here overrides the Basic tab.': '经过测试的默认值适用于大多数玩家。请仅按指南或问题排查要求修改。此处的设置将覆盖“基本”页的值。',
 'No description.': '暂无说明。',
 'Nothing to fill in.': '无需填写。',
 'Not available yet': '暂不可用',
 'Soon': '即将推出',
 'Show all': '显示全部',
 'Show the command': '显示命令',
 'Copy the log': '复制日志',
 'Open the Received folder': '打开接收文件夹',
 'Switch keys added': '已添加 Switch 密钥',
 'Add your Switch keys': '添加 Switch 密钥',
 'Choose prod.keys in Settings.': '请在设置中选择 prod.keys。',
 'Choose your prod.keys in Settings.': '请在设置中选择自己的 prod.keys。',
 'No board found. Plug it in, or pick one on the Board page.': '未找到开发板。请连接开发板，或在“开发板”页选择一个。',
 'Pokemon to offer': '用于交换的宝可梦',
 "The session's output appears here.": '会话输出显示在此处。',
 'Session': '会话',
 'On the console': '在游戏机上操作',
 'Before you start': '开始前',
 'Received': '已接收',
 'Offering': '正在提供',
 'Output': '输出',
 'Ready': '就绪',
 'Ready to start': '准备就绪',
 'Idle': '空闲',
 'Running': '运行中',
 'Start': '开始',
 'Stop': '停止',
 'Stopped': '已停止',
 'Not started': '尚未开始',
 'Finished': '已完成',
 'Check the options': '检查选项',
 'Read the docs for this game': '阅读此游戏的文档',
 'Before you send': '发送前',
 'Gift': '礼物',
 'Save gift file': '保存礼物文件',
 'Save Mystery Gift': '保存神秘礼物',
 'Here you go!': '请收下！',
 'Card id': '卡片 ID',
 'Customize': '自定义',
 'Card icon': '卡片图标',
 "Leave empty to keep the file's own icon.": '留空保留文件的原有图标。',
 'Text on the card': '卡片文字',
 'Can be received again': '允许重复领取',
 'Otherwise once per save.': '否则每个存档只能领取一次。',
 'The player can share it': '允许玩家分享',
 'Mystery Gift, Wonder Cards, Send.': '神秘礼物 → 神奇卡片 → 发送。',
 'The card': '卡片',
 'Who hands it over': '赠送者',
 'What happens': '效果',
 'Earlier': '前移',
 'Later': '稍后',
 'Remove': '移除',
 'Text, up to ten lines': '文字（最多十行）',
 'A console keeps news only when it differs from the one it holds; change the id to send the same text again.': '游戏机仅保存与现有内容不同的神奇新闻。若要再次发送相同文字，请更改 '
                                                                                                                'ID。',
 'ARM code runs on the console while it receives, every frame until it returns 1. A fault or a loop hangs the Mystery Gift menu, so it is run offline first.': '接收时，游戏机会逐帧运行 '
                                                                                                                                                               'ARM '
                                                                                                                                                               '代码，直到返回 '
                                                                                                                                                               '1。错误或死循环会使神秘礼物菜单卡住，因此发送前需要离线检查。',
 'Assembly': '汇编代码',
 'Or a prebuilt .bin (used instead of the assembly)': '或使用已编译的 .bin（替代汇编代码）',
 'Check again': '重新检查',
 'Check offline': '离线检查',
 'Expected answer': '预期结果',
 'Bytes sent back': '返回字节',
 'Built for': '目标版本',
 'The Pokemon arrives shiny.': '收到的宝可梦为异色。',
 'Add an item': '添加道具',
 'Battle Points': '对战点数',
 'Homebrew': '自制程序',
 'Item': '道具',
 'How many': '数量',
 'Sword and Shield': '剑／盾',
 'Sword/Shield .wc8': '剑／盾 .wc8',
 'Title': '标题',
 'Subtitle': '副标题',
 'Icon': '图标',
 'Message': '消息',
 'News id': '新闻 ID',
 'Any cartridge': '任意卡带',
 "{PLAYER} is the player's name. A box holds two lines.": '{PLAYER} 代表玩家姓名。每个文本框可容纳两行。',
 'Typing assembly here needs the free GNU Arm assembler. Install it once: ': '输入汇编代码需要免费的 GNU Arm 汇编器。安装一次即可：',
 '. A prebuilt .bin works without it.': '。使用已编译的 .bin 无需安装。',
 'Assembled with the GNU Arm toolchain on this computer.': '使用此电脑上的 GNU Arm 工具链编译。',
 'paste this in a terminal, then check again': '将此命令粘贴到终端执行，然后重新检查',
 "download it from Arm's page, then check again": '从 Arm 官网下载，然后重新检查',
 "Arm's download page": 'Arm 下载页面',
 'Checking…': '正在检查…',
 'Preparing gift file…': '正在准备礼物文件…',
 'Checking...': '正在检查…',
 'Copied': '已复制',
 'Browse': '浏览',
 'Copy code': '复制代码',
 'Start here': '入门指南',
 'Open the docs website': '打开文档网站',
 'Welcome to pokeldn': '欢迎使用 pokeldn',
 'Trade and send gifts over local wireless, right from your computer.': '直接通过电脑，以本地无线通信交换宝可梦和发送礼物。',
 'Choose prod.keys dumped from your own console. The keys decrypt local wireless messages and stay on this computer.': '选择从自己的游戏机导出的 '
                                                                                                                       'prod.keys。密钥用于解密本地无线通信消息，并保存在此电脑上。',
 'Plug in your ESP32 with a USB data cable.': '使用 USB 数据线连接 ESP32。',
 'Pick a game, choose a tool and follow the console steps.': '选择游戏和功能，然后按照游戏机操作步骤进行。',
 'Update available': '有可用更新',
 "What's new": '更新内容',
 'Download': '下载',
 'Close welcome': '关闭欢迎页面',
 'Read the setup guide': '阅读设置指南',
 'Your settings, keys and received Pokemon stay where they are.': '设置、密钥和已接收的宝可梦将保留在原位置。',
 'Download the new version, then replace this app with it. ': '下载新版本，然后替换当前应用。',
 'Download the new version for your computer from the release page, then replace this app with it. ': '从发布页面下载适用于此电脑的新版本，然后替换当前应用。',
 'Choose prod.keys': '选择 prod.keys',
 'Drop prod.keys here, or add keys later in Settings.': '将 prod.keys 拖放到此处，或稍后在设置中添加密钥。',
 'Add keys later in Settings.': '稍后可在设置中添加密钥。',
 'Your setup': '基础设置',
 'Switch keys': 'Switch 密钥',
 'prod.keys dumped from your own console. Needed to talk to the games; it never leaves this computer.': '从自己的游戏机导出的 '
                                                                                                        'prod.keys，用于与游戏通信，仅保存在此电脑上。',
 'Your trainer': '原始训练家',
 'The original trainer of every Pokemon the app builds for you. Put your own name and IDs to make them yours; the IDs were drawn at random on first launch.': '应用生成宝可梦时使用的原始训练家。填写自己的姓名和 '
                                                                                                                                                              'ID '
                                                                                                                                                              '即可将其设为自己的宝可梦；ID '
                                                                                                                                                              '在首次启动时随机生成。',
 'Trainer ID': '训练家 ID',
 'Secret ID': '里 ID',
 'Name': '姓名',
 'Language': '语言',
 'Received Pokemon': '已接收的宝可梦',
 'Where the Pokemon a console sends you are saved.': '保存游戏机发送过来的宝可梦的位置。',
 'Storage': '存储',
 'Local files': '本地文件',
 'Clear local files': '清理本地文件',
 'Clear local files?': '清理本地文件？',
 'Clear files': '清理文件',
 'Checking local files...': '正在检查本地文件…',
 'Clearing local files...': '正在清理本地文件…',
 'No local files to clear.': '没有可清理的本地文件。',
 ' Some folders could not be read.': '部分文件夹无法读取。',
 ' Files in use or changed since the check were kept.': '正在使用或检查后已修改的文件予以保留。',
 'Finish the current run or board check before clearing local files.': '请先完成当前运行或开发板检查，再清理本地文件。',
 'Free space used by session records, logs, temporary offers and unused built Pokemon. Your received Pokemon, selected offers, keys, firmware and settings are kept.': '清理会话记录、日志、临时交换文件及未使用的已生成宝可梦。保留已接收的宝可梦、已选择的交换文件、密钥、固件和设置。',
 'Bug reports': '问题报告',
 'Record every session': '记录每次会话',
 'Keeps a small record of each session. When something fails, attach the latest file to your report.': '为每次会话保存简要记录。发生错误时，请将最新记录附在问题报告中。',
 'Open the records': '打开记录文件夹',
 'Hide advanced settings': '隐藏高级设置',
 'Show advanced settings': '显示高级设置',
 'Serial speed': '串口波特率',
 'How fast the computer talks to the board. Keep the default unless a guide says otherwise.': '电脑与开发板的通信速率。除非指南另有要求，请保留默认值。',
 "Record the board's serial traffic": '记录开发板串口通信',
 "Adds the board's counters and every serial message to the session record. Only for radio problems someone asked you to report.": '在会话记录中加入开发板计数器和每条串口消息。仅在排查无线通信问题时按要求启用。',
 'Pokemon sprites': '宝可梦图像',
 'Clear the cache': '清除缓存',
 'Pixel-art sprites come from PokeAPI and are kept on this computer after the first download. The app works without them.': '像素图像来自 '
                                                                                                                            'PokeAPI，首次下载后缓存在此电脑上。没有图像也能使用应用。',
 'Check now': '立即检查',
 'Asks GitHub for a newer pokeldn when the app starts. Nothing about you or your games is sent.': '应用启动时向 GitHub '
                                                                                                  '查询 pokeldn '
                                                                                                  '新版本，不发送个人或游戏信息。',
 'GitHub did not answer. Check your connection.': 'GitHub 未响应，请检查网络连接。',
 'pokeldn is AGPLv3. Pokemon are checked with PKHeX.Core (GPLv3).': 'pokeldn 使用 AGPLv3 许可，宝可梦由 '
                                                                    'PKHeX.Core（GPLv3）检查。',
 '921600 (default)': '921600（默认）',
 '1500000 (faster, needs a good cable)': '1500000（更快，需要优质数据线）',
 'Open it': '打开文件夹',
 'Found': '已找到',
 'No file at this path': '此路径下没有文件',
 'Sprite not available. It downloads once when the app is online.': '图像暂不可用。应用联网后会下载并缓存。',
 'Sprite downloads are off in Settings.': '设置中已关闭图像下载。',
 'No sprite for this species.': '此种类没有图像。',
 'No pokeldn firmware': '未检测到 pokeldn 固件',
 'Port busy or not allowed': '端口被占用或无权限',
 'Port not allowed': '无端口访问权限',
 'Checking the board': '正在检查开发板',
 'Asking the board for its firmware.': '正在查询开发板固件。',
 'No board plugged in': '未连接开发板',
 'Plug the ESP32 in with a USB data cable. Charge-only cables show nothing.': '请使用 USB 数据线连接 '
                                                                              'ESP32。仅支持充电的线缆无法识别开发板。',
 'Several boards plugged in': '连接了多个开发板',
 'Open the Board page and pick the one to use.': '打开“开发板”页，选择要使用的开发板。',
 'Board unplugged': '开发板已断开',
 'Plug it back in.': '请重新连接。',
 'Firmware out of date': '固件版本过旧',
 'Flash the board to update it.': '请刷写开发板以更新固件。',
 'Unplug and replug the board.': '请拔出并重新连接开发板。',
 'No permission to open the board': '无权访问开发板',
 'Board port busy': '开发板端口被占用',
 'Another program holds the port. Close it, or unplug and replug the board.': '其他程序占用了端口。请关闭该程序，或拔出并重新连接开发板。',
 'No pokeldn firmware on the board': '开发板未安装 pokeldn 固件',
 'Flash the board. If you just flashed it, press its RESET (RST) button.': '请刷写开发板。如果刚刚刷写完成，请按 RESET（RST）按钮。',
 "Use the board's other USB port": '请使用开发板的另一个 USB 接口',
 'Board found without a serial port': '已找到开发板，但没有串口',
 'Board ready': '开发板已就绪',
 'ESP32-S3, C3 or C6 with two USB ports: plug into the one marked USB, not COM or UART.': 'ESP32-S3、C3 或 C6 若有两个 '
                                                                                          'USB 接口，请连接标有 USB '
                                                                                          '的接口，避开 COM 或 UART 接口。',
 'Press Flash. The app picks the firmware for your chip and checks the board afterwards.': '点击“刷写”。应用会选择适合芯片的固件，并在完成后检查开发板。',
 "Stuck on 'Connecting'? Hold the board's BOOT button until writing starts, then let go.": '卡在“连接中”？按住开发板的 BOOT '
                                                                                           '按钮，直到开始写入后松开。',
 'Checks and flashing show their output here.': '检查和刷写的输出显示在此处。',
 'Details': '详情',
 "Blink the LED shows which board this is: a classic ESP32's blue LED blinks for five seconds. A nickname helps when several are plugged in.": '点击“闪烁 '
                                                                                                                                               'LED”可识别开发板：经典 '
                                                                                                                                               'ESP32 '
                                                                                                                                               '的蓝色 '
                                                                                                                                               'LED '
                                                                                                                                               '会闪烁五秒。连接多个开发板时，可使用昵称区分。',
 'Board not listed?': '没有看到开发板？',
 'Checking': '检查中',
 'Living room, spare...': '客厅、备用…',
 'Flashing...': '正在刷写…',
 'Flash': '刷写',
 'Flash the firmware': '刷写固件',
 'Needed once per board, and again after an app update that says so. Takes about thirty seconds.': '每个开发板首次使用时需要刷写一次；应用更新提示需要时再次刷写。约需三十秒。',
 'Done. Checking the board...': '写入完成，正在检查开发板…',
 'Flashing failed. Hold the BOOT button and press Flash again; the Activity log has the details.': '刷写失败。请按住 BOOT '
                                                                                                   '按钮并再次点击“刷写”。详情见活动日志。',
 'Use this board': '使用此开发板',
 'Go to Games': '前往游戏页',
 'not checked yet': '尚未检查',
 'Port': '端口',
 'USB chip': 'USB 芯片',
 'Firmware': '固件',
 'Wi-Fi MAC': 'Wi-Fi MAC 地址',
 'Try another cable or USB port. Many cables only charge.': '请尝试其他数据线或 USB 接口。许多线缆仅支持充电。',
 "Windows and macOS need the driver for the board's USB chip:": 'Windows 和 macOS 需要安装开发板 USB 芯片驱动：',
 'Linux: allow serial ports, then log out and back in:': 'Linux：授予串口权限，然后注销并重新登录：',
 'Arch and its derivatives name the group uucp instead of dialout.': 'Arch 及其衍生发行版使用 uucp 用户组，而不是 dialout。',
 'Use a classic ESP32 (ESP32-D0WD, WROOM-32E), or an ESP32-S3, C3 or C6 through its native USB port. S2 boards are not supported.': '请使用经典 '
                                                                                                                                    'ESP32（ESP32-D0WD、WROOM-32E），或通过原生 '
                                                                                                                                    'USB '
                                                                                                                                    '接口连接 '
                                                                                                                                    'ESP32-S3、C3、C6。不支持 '
                                                                                                                                    'S2 '
                                                                                                                                    '开发板。',
 'Blink the LED': '闪烁 LED',
 'Firmware included with the app: ESP32, ESP32-S3, ESP32-C3 or ESP32-C6, picked for your chip.': '应用附带 '
                                                                                                 'ESP32、ESP32-S3、ESP32-C3、ESP32-C6 '
                                                                                                 '固件，会根据芯片自动选择。',
 'No firmware image here yet (a copy run from source). Download the released one; no ESP-IDF needed.': '当前没有固件镜像（从源码运行）。请下载发布版固件，无需安装 '
                                                                                                       'ESP-IDF。',
 'Activity': '活动',
 'No board found': '未找到开发板',
 'Plug it in with a data cable. It shows up here on its own.': '使用数据线连接后，开发板会自动显示在此处。',
 'Save the nickname': '保存昵称',
 'Included firmware': '附带固件',
 'Scan again': '重新扫描',
 'In use': '使用中',
 'Use a firmware file of your own': '使用自己的固件文件',
 ', or drop a .bin on this card': '，或将 .bin 拖放到此卡片',
 'Downloading...': '正在下载…',
 'Download the firmware': '下载固件',
 'English': '英语',
 'French': '法语',
 'German': '德语',
 'Italian': '意大利语',
 'Spanish': '西班牙语',
 'Japanese': '日语',
 'Korean': '韩语',
 'FireRed': '火红',
 'LeafGreen': '叶绿',
 'FireRed & LeafGreen': '火红／叶绿',
 "Let's Go Pikachu & Eevee": "Let's Go! 皮卡丘／伊布",
 'Sword & Shield': '剑／盾',
 'Brilliant Diamond & Shining Pearl': '晶灿钻石／明亮珍珠',
 'Legends Arceus': '传说 阿尔宙斯',
 'Scarlet & Violet': '朱／紫',
 'Legends Z-A': '传说 Z-A',
 'Version': '版本',
 'Channel': '信道',
 'Console': '游戏机',
 'Time limit (seconds)': '时间限制（秒）',
 'Link code': '连接密码',
 'Link Code': '连接密码',
 'Room password': '房间密码',
 'New PID each run': '每次运行使用新 PID',
 'Use a preset': '使用预设',
 'Build your own': '自行制作',
 'Open a file': '打开文件',
 'The wireless channel of the network pokeldn hosts.': 'pokeldn 创建的网络所使用的无线信道。',
 'The same code the player enters on the console.': '与玩家在游戏机上输入的密码一致。',
 'Pick a species; PKHeX builds a legal one for this game.': '选择种类，由 PKHeX 生成适用于此游戏的合法宝可梦。',
 "Pick a species; PKHeX builds a legal one. Empty offers pokeldn's own Azelf.": '选择种类，由 PKHeX 生成合法宝可梦。留空则提供 '
                                                                                'pokeldn 的亚克诺姆。',
 'Pick a species; PKHeX builds a legal one. Empty offers your own first party Pokemon back, renamed POKELDN.': '选择种类，由 '
                                                                                                               'PKHeX '
                                                                                                               '生成合法宝可梦。留空则返还队伍中的第一只宝可梦，并将昵称改为 '
                                                                                                               'POKELDN。',
 'Offer the Pokemon under a new PID and encryption constant, so a save that already received it takes it again. Turn it off for a file whose PID must stay, such as an event Pokemon.': '为交换的宝可梦生成新的 '
                                                                                                                                                                                        'PID '
                                                                                                                                                                                        '和加密常量，使已领取过的存档可以再次接收。活动宝可梦等必须保留 '
                                                                                                                                                                                        'PID '
                                                                                                                                                                                        '的文件，请关闭此选项。',
 'How long the host stays up after Start, then it closes on its own. Leave time for every trade in the queue.': '点击“开始”后主机运行的时长，到时自动关闭。请为队列中的每次交换预留时间。',
 'How long the joiner stays connected once it joins the console, then it leaves on its own.': '加入游戏机后保持连接的时长，到时自动离开。',
 'A trade under way when it runs out is finished first.': '到时若正在交换，会先完成该次交换。',
 'How long the card is advertised after Start.': '点击“开始”后卡片广播的时长。',
 'Eight digits. Empty for a plain trade.': '八位数字。留空进行无密码交换。',
 'Eight digits. Empty for the plain room.': '八位数字。留空加入无密码房间。',
 'Empty joins a search with no code.': '留空加入无密码搜索。',
 'Empty hosts a search with no code.': '留空创建无密码搜索。',
 'A nickname given to every offered Pokemon; empty keeps the one it was built with.': '为所有交换的宝可梦设置昵称；留空保留生成时的昵称。',
 "The game pokeldn's own trainer reports on the link, and the one the Pokemon is built for.": 'pokeldn '
                                                                                              '的训练家在连接中报告的游戏版本，也是生成宝可梦的目标版本。',
 "The language pokeldn's own trainer reports on the link.": 'pokeldn 的训练家在连接中报告的语言。',
 "The console's cartridge: another one is refused before anything is sent.": '游戏机使用的卡带版本；版本不符时会在发送前拒绝连接。',
 'The three Pokemon the player picks on the console, in the same order.': '玩家在游戏机上选择的三只宝可梦，顺序必须一致。',
 "Host a Direct Corner trade. The console joins pokeldn's group.": '创建直接大厅交换，游戏机加入 pokeldn 的组。',
 'Join a trade group the console leads.': '加入由游戏机创建的交换组。',
 'Send a Wonder Card, Wonder News or console code: pick a preset or build your own.': '发送神奇卡片、神奇新闻或游戏机代码：选择预设或自行制作。',
 'Host a trade under a link code; the console joins.': '使用连接密码创建交换，由游戏机加入。',
 "Join the console's trade search.": '加入游戏机的交换搜索。',
 'Advertise a Wonder Card: pick a preset or build your own. The console reads it off the air.': '广播神奇卡片：选择预设或自行制作，游戏机通过无线通信接收。',
 "Join the console's Link Trade search.": '加入游戏机的连接交换搜索。',
 'Host a Link Trade the console joins.': '创建连接交换，由游戏机加入。',
 "Join the console's Union Room as a character and trade.": '以角色身份加入游戏机的联盟房间并交换。',
 'Host a Union Room the console enters.': '创建联盟房间，由游戏机进入。',
 "Join the console's search. It hands pokeldn the host role, which the joiner takes on its own.": '加入游戏机的搜索。游戏机会移交主机角色，pokeldn '
                                                                                                  '自动接管。',
 'Host a trade the searching console joins.': '创建交换，由正在搜索的游戏机加入。',
 'Pokemon Center 2F, third attendant, Direct Corner, Trade Center': '宝可梦中心二楼 → 第三位接待员 → 直接大厅 → 交换中心',
 'X, Communicate, Local Communication, Trade, enter the same link code, then search.': 'X → 通信 → 本地通信 → '
                                                                                       '交换，输入相同的连接密码并搜索。',
 'Pokemon Center 2F, left attendant, plain Yes (no password, not the group option).': '宝可梦中心二楼 → 左侧接待员 → '
                                                                                      '选择普通的“是”（无密码，非群组选项）。',
 'X, Poke Portal, Link Trade, offline, then search.': 'X → 宝可入口站 → 连接交换，在离线状态下搜索。',
 'Talk to the trade NPC in Jubilife Village: trade, local, past the warning.': '与祝庆村的交换 NPC 对话：交换 → 本地通信 → 确认提示。',
 'Enter the same eight-digit code and press + to search.': '输入相同的八位密码，按 + 搜索。',
 "Start the host and wait for 'Hosting Direct Corner' in the log.": '启动主机，等待日志出现“Hosting Direct Corner”。',
 'Choose the Pokemon to trade and confirm.': '选择要交换的宝可梦并确认。',
 'With several queued, trade again after each save; the host offers the next one.': '若队列中有多只宝可梦，每次保存后再次交换；主机会提供下一只。',
 "Back on the trade menu after the last save, wait for the host's prompt, then Cancel and Yes.": '最后一次保存后返回交换菜单，等待主机提示，再选择“取消”并确认“是”。',
 'Start the joiner first: it scans until the console appears.': '先启动加入端，它会扫描直到发现游戏机。',
 'Accept POKELDN when it appears, then choose and confirm.': '看到 POKELDN 后接受连接，再选择宝可梦并确认。',
 'With several queued, trade again after each save; the joiner offers the next one.': '若队列中有多只宝可梦，每次保存后再次交换；加入端会提供下一只。',
 'Title screen: Mystery Gift, Wonder Cards, Friend. For news: the second entry, Wonder News.': '标题画面 → 神秘礼物 → '
                                                                                               '神奇卡片 → '
                                                                                               '朋友。接收新闻时选择第二项“神奇新闻”。',
 'Start the host, then pick POKELDN when it appears.': '启动主机，看到 POKELDN 后选择它。',
 'Answer Yes if the console asks to replace its card.': '游戏机询问是否替换卡片时，选择“是”。',
 'Console code: keep the host running until the log shows the result.': '发送游戏机代码时，请保持主机运行，直到日志显示结果。',
 'Back out of the search screen between two runs.': '两次运行之间，请退出搜索画面。',
 'Start the host first.': '先启动主机。',
 'Choose a Pokemon and confirm.': '选择宝可梦并确认。',
 'Start the joiner: it scans for up to five minutes.': '启动加入端，最多扫描五分钟。',
 'Offer and confirm once POKELDN shows. Queued Pokemon follow, one per trade.': '看到 POKELDN '
                                                                                '后选择宝可梦并确认。队列中的宝可梦将依次提供，每次交换一只。',
 'Mystery Gift, Receive a Gift, via local wireless.': '神秘礼物 → 接收礼物 → 通过本地无线通信接收。',
 'Start the host: the card is listed within a few seconds or not at all.': '启动主机，卡片通常在几秒内出现；若未出现，请重新尝试。',
 'Accept the card, then stop the host.': '接收卡片后停止主机。',
 'Y-Comm, Link Trade, local communication, no code; press A on both messages.': 'YY 通讯 → 连接交换 → 本地通信，不设置密码；两条提示均按 '
                                                                                'A 确认。',
 'Start the joiner while the console searches.': '游戏机搜索时启动加入端。',
 'POKELDN appears on the trade screen: choose a Pokemon and confirm.': '交换画面出现 POKELDN 后，选择宝可梦并确认。',
 'Queued Pokemon follow, one per trade: pick again from the box.': '队列中的宝可梦依次交换，每次一只；请再次从盒子中选择。',
 'Start the host and wait for the network to come up.': '启动主机，等待网络建立。',
 'Y-Comm, Link Trade, local communication; press A on both messages, then wait in the overworld.': 'YY 通讯 → 连接交换 '
                                                                                                   '→ 本地通信；两条提示均按 '
                                                                                                   'A，然后在地图中等待。',
 'Choose a Pokemon and confirm when POKELDN appears.': '看到 POKELDN 后选择宝可梦并确认。',
 'Start the joiner and wait for the character to appear.': '启动加入端，等待角色出现。',
 'Y, Communicate, Trade Pokemon, and wait: the greeting comes up on its own.': 'Y → 通信 → 交换宝可梦，等待自动出现问候。',
 'Between runs, leave and re-enter the room.': '两次运行之间，请离开并重新进入房间。',
 'Start the host before the player enters the room.': '玩家进入房间前启动主机。',
 'Y, Communicate, Trade Pokemon; accept the greeting, then choose and confirm.': 'Y → 通信 → 交换宝可梦，接受问候，再选择并确认。',
 'Offer a Pokemon and confirm.': '选择要提供的宝可梦并确认。',
 'Leave the host running until the trade ends: an interrupted trade locks trading for a while.': '保持主机运行直到交换完成。中断交换会导致一段时间内无法交换。',
 'Start the joiner.': '启动加入端。',
 'Offer and confirm once the partner shows.': '交换对象出现后，选择宝可梦并确认。',
 'Offer and confirm on the trade screen.': '在交换画面选择宝可梦并确认。',
 'If the console keeps refusing, leave and re-enter the search screen.': '若游戏机持续拒绝连接，请退出并重新进入搜索画面。',
 'Link Trade, local communication, search with the link code.': '连接交换 → 本地通信，使用连接密码搜索。',
 'Start the joiner. Refusals while seating are normal; let it run.': '启动加入端。建立连接时被拒绝属于正常现象，请保持运行。',
 'Pick on the trade box and confirm once PKLDN appears. Queued Pokemon follow, one per trade.': '看到 PKLDN '
                                                                                                '后在交换盒子中选择并确认。队列中的宝可梦依次交换，每次一只。',
 'X, Link Play, Link Trade, Nearby Players, the same code, then search.': 'X → 连接游玩 → 连接交换 → 附近的玩家，输入相同密码并搜索。',
 'Pick on the trade box, offer, then trade. Queued Pokemon follow, one per trade.': '在交换盒子中选择宝可梦，提出交换并确认。队列中的宝可梦依次交换，每次一只。',
 'Back out with B after the last trade.': '最后一次交换后按 B 退出。',
 ', Join Group, then pick POKELDN.': ' → 加入组，然后选择 POKELDN。',
 ', Become Leader.': ' → 成为组长。',
 ' Wait in the room, clear of the walls.': '在房间内等待，并远离墙壁。',
 ' Our character appears.': '等待 pokeldn 的角色出现。',
 ' Add a trade to queue more: one session trades them in order.': '点击“添加交换”加入队列，同一会话将按顺序交换。',
 ' Pick a species, then press Build.': '选择种类，然后点击“生成”。',
 'Trade ': '交换 ',
 'Set ': '配置 ',
 'Slot ': '位置 ',
 'Imported ': '已导入 ',
 '. Check the options below, then press Build.': '。检查下方选项，然后点击“生成”。',
 ' files dropped; the first was used.': ' 个文件已拖入，已使用第一个。',
 'Not a Pokemon this game can take: ': '此游戏无法接收该宝可梦：',
 'Could not read ': '无法读取 ',
 ' of ': ' / ',
 ', traded in this order': '，按此顺序交换',
 'Up to ': '最多 ',
 ' Pokemon in one session': ' 只宝可梦可在同一会话中交换',
 ' did not fit: one session trades at most ': ' 只未加入：每次会话最多交换 ',
 'The paste holds ': '粘贴内容包含 ',
 ' Pokemon; the others went to ': ' 只宝可梦，其余已加入交换 ',
 ' Pokemon; only the first fit.': ' 只宝可梦，仅第一只可加入。',
 ' Pokemon; the first was imported.': ' 只宝可梦，已导入第一只。',
 ' set': ' 项已设置',
 ' in all': ' 合计',
 'EVs add up to at most ': '努力值总和最多为 ',
 '; or drop files here': '；也可将文件拖放到此处',
 'About pokeldn ': '关于 pokeldn ',
 ' files removed': ' 个文件已删除',
 ' files removed.': ' 个文件已删除。',
 ' files': ' 个文件',
 'Freed ': '已释放 ',
 ' can be freed · ': ' 可释放 · ',
 'Could not clear local files: ': '无法清理本地文件：',
 ' files could not be removed; try again.': ' 个文件无法删除，请重试。',
 'You have the latest version (': '当前已是最新版本（',
 ' is available.': ' 已发布。',
 'Remove ': '删除 ',
 ' files and free about ': ' 个文件，约可释放 ',
 '. This deletes saved session records, logs, temporary offers and unused built Pokemon. Save any records needed for a bug report first. Your received Pokemon, selected offers, keys, firmware and settings are kept.': '。将删除已保存的会话记录、日志、临时交换文件和未使用的已生成宝可梦。请先保存问题报告需要的记录。保留已接收的宝可梦、已选择的交换文件、密钥、固件和设置。',
 ' is available': ' 已发布',
 'You have ': '当前版本：',
 ' Sessions use this board.': '会话使用此开发板。',
 ' Sessions use another board; press Use this board to switch.': '会话正在使用另一个开发板，点击“使用此开发板”切换。',
 'Custom image: ': '自定义镜像：',
 ' is ready. Press Flash.': '已就绪，请点击“刷写”。',
 '[app] Could not download the firmware: ': '[app] 无法下载固件：',
 'Saved ': '已保存 ',
 'Line ': '行 ',
 'Move ': '招式 ',
 'Works on ': '适用于 ',
 ' Wonder Card.': ' 神奇卡片。',
 'A .pokegift someone shared, or a ': '他人分享的 .pokegift，或一个 ',
 ' traded': ' 次交换已完成',
 ' trades, in order': ' 次交换，按顺序进行',
 ' (done)': '（已完成）',
 'Running ': '正在运行 ',
 'Stop ': '停止 ',
 ' and start': ' 并开始',
 'Could not read the options: ': '无法读取选项：',
 'Not read by PKHeX · ': 'PKHeX 无法读取 · ',
 'Failed (': '失败（',
 'Official events': '官方活动',
 'Has settings': '可设置',
 'All': '全部',
 'Room on the console': '游戏机可用空间',
 ' bytes': ' 字节',
 ' cards': ' 张卡片',
 'Search: Pikachu, Master Ball, shiny...': '搜索：皮卡丘、大师球、异色…',
 "Real event cards from the projectpokemon EventsGallery archive. Each one passed the game's own card check.": '来自 '
                                                                                                               'projectpokemon '
                                                                                                               'EventsGallery '
                                                                                                               '存档的真实活动卡片，均已通过游戏自身的卡片检查。',
 'These boosts are always saved in your game. ': '这些增强功能始终保存在游戏存档中。',
 'The selected boosts run together. Sending a new selection replaces the boosts already running.': '所选增强功能同时运行。发送新的组合会替换正在运行的增强功能。',
 'Starts on the console as soon as it is received.': '游戏机接收后立即生效。',
 'It can Gigantamax; only species with a Gigantamax form.': '允许超极巨化；仅适用于具有超极巨化形态的种类。',
 'Official outfits. A card holds six pieces for each gender; the player gets the version for their own.': '官方服装。每张卡片可为每种性别包含六件服装，玩家收到与自身角色对应的版本。',
 'Gigantamax': '超极巨化',
 'Clothing': '服装',
 'Pokemon': '宝可梦',
 'Pokemon egg': '宝可梦的蛋',
 'Egg': '蛋',
 'Items': '道具',
 'Wild battle': '野生对战',
 'Wonder Card': '神奇卡片',
 'Wonder Cards': '神奇卡片',
 'Wonder News': '神奇新闻',
 'Console code': '游戏机代码',
 'Event Pokemon': '活动宝可梦',
 '10th Anniversary Pokemon': '十周年活动宝可梦',
 'Change a Pokemon': '修改宝可梦',
 'Game changes': '游戏设置修改',
 'More gifts': '更多礼物',
 'Read the save': '读取存档',
 'Game boosts': '游戏增强',
 'Game speed': '游戏速度',
 'Where': '生效范围',
 'When': '启用方式',
 'Always on': '始终启用',
 'Hold R': '按住 R',
 'Hold B (also runs)': '按住 B（同时跑步）',
 'Hold Select (also uses the registered item)': '按住 Select（同时使用登录道具）',
 'Overworld and battles': '地图与对战',
 'Overworld only': '仅地图',
 'Battles only': '仅对战',
 'Faster text': '加速文字',
 'Dialogue prints several letters a frame.': '对话每帧显示多个字符。',
 'Slow the game down': '降低游戏速度',
 'By': '减速倍率',
 'x2 slower': '减速至 1/2',
 'x4 slower': '减速至 1/4',
 'x8 slower': '减速至 1/8',
 'Save boosts for later': '保存增强功能供以后使用',
 'Mom restores your boosts': '由妈妈恢复增强功能',
 'Speed up the game': '加速游戏',
 "Lead's IVs on screen": '显示队首宝可梦的个体值',
 'Shiny countdown': '异色倒计时',
 'Walk through walls': '穿墙',
 'No wild encounters': '关闭野生遭遇',
 'Pokemon follower': '宝可梦跟随',
 'The delivery man': '配送员',
 'Mom': '妈妈',
 'The man in Pallet Town': '真新镇的男子',
 'any Pokemon Center, after the card is saved': '保存卡片后的任意宝可梦中心',
 "the player's house": '玩家家中',
 'south of Pallet Town': '真新镇南侧',
 'FireRed (French)': '火红（法语）',
 'LeafGreen (French)': '叶绿（法语）',
 'FireRed (English)': '火红（英语）',
 'LeafGreen (English)': '叶绿（英语）',
 'FireRed (Spanish)': '火红（西班牙语）',
 'Legendary beast': '传说的三圣兽',
 'Master Ball': '大师球',
 'Altering Cave': '变化洞窟',
 'Porygon TM gift': '多边兽与招式学习器',
 'Sun and Moon Rally: Solrock': '日月集章：太阳岩',
 'Sun and Moon Rally: Lunatone': '日月集章：月石',
 'Visiting trainer': '来访训练家',
 'Battle count card': '对战计数卡片',
 'Worlds XP': '世界锦标赛 XP',
 'One berry in Cerulean City': '华蓝市的一颗树果',
 'Ten-line news': '十行新闻',
 'Wish Egg': '祈愿蛋',
 'PokePark egg': '宝可梦乐园的蛋',
 'Pokemon Center Japan egg': '日本宝可梦中心的蛋',
 'Starter egg': '初始伙伴的蛋',
 'Rare berries': '稀有树果',
 'National Pokedex': '全国图鉴',
 'Nature mint': '性格薄荷',
 'Ability capsule': '特性胶囊',
 'Poke Ball changer': '更换精灵球',
 'Gender change': '更改性别',
 'Nickname change': '更改昵称',
 'IV and EV judge': '个体值与努力值鉴定',
 'Hidden Power and max IVs': '觉醒力量与满个体值',
 'Hidden Power type': '觉醒力量属性',
 'EV training': '努力值训练',
 'Friendship checker': '亲密度检查',
 'PP Max': 'PP 极限提升',
 'Max conditions': '最大华丽大赛能力',
 'Pokerus': '宝可病毒',
 'Unown letter': '未知图腾字母',
 'Trade evolution': '连接交换进化',
 'Espeon or Umbreon': '太阳伊布或月亮伊布',
 'Move relearner and deleter': '回忆与忘记招式',
 'Double speed': '两倍速',
 'Triple speed': '三倍速',
 'Quadruple speed': '四倍速',
 'Slower game': '减慢游戏',
 'Half speed': '半速',
 'Fast text': '快速文字',
 'Fly with R': '按 R 飞翔',
 'PC anywhere': '随时使用电脑',
 'HM moves without HMs': '无需秘传学习器的秘传招式',
 'Reusable TMs': '招式学习器可重复使用',
 'Physical/special split': '物理／特殊分类',
 'Exp. Share for all': '全队分享经验',
 'Shiny chain': '异色连锁',
 'Roaming Pokemon finder': '寻找游走宝可梦',
 'No encounters or repel': '关闭遭遇或驱虫',
 'Legendary respawn': '传说宝可梦重新出现',
 'Instant eggs': '即时孵蛋',
 'Gift box': '礼物箱',
 'Pocket casino': '随身游戏厅',
 'Gift ribbons': '活动奖章',
 'Trainer ID and Secret ID on screen': '显示训练家 ID 与里 ID',
 'New trainer name or look': '更改训练家姓名或外观',
 'Rename your rival': '更改劲敌姓名',
 'Pokemon Box eggs': 'Pokémon Box 的蛋',
 'Colosseum Pikachu': '竞技场皮卡丘',
 'AGETO Celebi': 'AGETO 时拉比',
 'MATTLE Ho-Oh': 'MATTLE 凤王',
 'Trainer ID (TID) and Secret ID (SID)': '训练家 ID（TID）与里 ID（SID）',
 'Trainer name, IDs and play time': '训练家姓名、ID 与游戏时间',
 "Your party's IVs and natures": '队伍的个体值与性格',
 'Two berries, a Master Ball and a battle with the beast that follows the starter.': '两颗树果、一个大师球，以及与初始伙伴对应的三圣兽对战。',
 'A level 50 Celebi from the delivery man.': '从配送员处领取等级 50 的时拉比。',
 'One Master Ball.': '一个大师球。',
 'Changes which Pokemon live in Altering Cave.': '改变变化洞窟中出现的宝可梦。',
 'One of six eggs that knows Wish, picked by the console.': '由游戏机从六种拥有祈愿招式的蛋中选择一个。',
 'One of fifteen eggs with special moves, picked by the console.': '由游戏机从十五种拥有特殊招式的蛋中选择一个。',
 'One of four eggs with special moves.': '四种拥有特殊招式的蛋之一。',
 'An egg of one of the nine first partners.': '九种初始伙伴的蛋之一。',
 'An Enigma, a Lansat and a Starf Berry.': '谜芝果、兰萨果和星桃果各一个。',
 'Upgrades the Pokedex to the National Pokedex.': '将图鉴升级为全国图鉴。',
 'A Porygon and a TM.': '一只多边兽和一个招式学习器。',
 'A rally stamp.': '一枚活动印章。',
 'A trainer who waits in the Pokemon Center.': '在宝可梦中心等待的训练家。',
 'A card that counts link battles.': '记录连接对战次数的卡片。',
 'The Worlds card.': '世界锦标赛卡片。',
 "Pick which stat a Pokemon's nature raises and lowers.": '选择宝可梦性格提升和降低的能力。',
 'Switches a Pokemon to its other ability.': '切换为宝可梦的另一种特性。',
 'Moves a Pokemon into the ball you choose.': '为宝可梦更换所选精灵球。',
 'Switches a Pokemon between male and female.': '切换宝可梦的雄性或雌性。',
 'A new nickname, or the species name back.': '设置新昵称，或恢复为种类名称。',
 "Shows a Pokemon's nature, six IVs and EVs on screen.": '显示宝可梦的性格、六项个体值和努力值。',
 'Shows its Hidden Power, then can set every IV to 31.': '显示觉醒力量，并可将所有个体值设为 31。',
 'Gives Hidden Power the type you pick.': '将觉醒力量设为所选属性。',
 'Resets EVs or maxes the stats you pick, no battles.': '重置努力值，或将所选能力的努力值设为最大，无需对战。',
 'Shows friendship and can max it.': '显示亲密度，并可设为最大。',
 'Every move in the party gets its most PP.': '将队伍中所有招式的 PP 提升至上限。',
 'Contest stats to the max; Feebas then evolves.': '将华丽大赛能力设为最大，丑丑鱼随后可进化。',
 'The party catches Pokerus, which doubles EVs earned.': '为队伍感染宝可病毒，使获得的努力值加倍。',
 'Gives an Unown any letter.': '将未知图腾变为任意字母形态。',
 'Evolves a trade-evolution Pokemon, no trade.': '无需交换，使通过交换进化的宝可梦进化。',
 'A friendly Eevee evolves into the one you pick.': '亲密度较高的伊布进化为所选形态。',
 'Relearn or forget a move; the move tutors teach again.': '回忆或忘记招式，并允许招式教学者再次教学。',
 'R turns double speed on and off.': '按 R 开启或关闭两倍速。',
 'R turns triple speed on and off.': '按 R 开启或关闭三倍速。',
 'R turns x4 speed on and off.': '按 R 开启或关闭四倍速。',
 'R plays a little slower.': '按 R 稍微减慢游戏。',
 'R plays at half speed.': '按 R 以半速运行。',
 'All text prints at once until the game is reset.': '立即显示全部文字，重置游戏后失效。',
 'R flies from outdoors, no HM; run and bike anywhere.': '在户外按 R 飞翔，无需秘传学习器；可随处跑步和骑车。',
 'R opens the Pokemon boxes from anywhere.': '随处按 R 打开宝可梦盒子。',
 'Cut, Surf, Strength and more with only the badge.': '仅凭徽章即可使用居合斩、冲浪、怪力等招式。',
 'Teaching a TM no longer uses it up.': '使用招式学习器教学后不会消耗它。',
 'Each move is physical or special as in later games.': '采用后续世代的招式物理／特殊分类。',
 'The whole party gets Exp. from every battle.': '每场对战后全队获得经验。',
 'Meeting one species again and again makes it shiny more often; R shows the chain.': '连续遇到同一种宝可梦可提高异色概率；按 R '
                                                                                      '查看连锁。',
 'Says where the roaming Pokemon is and can lure it.': '显示游走宝可梦的位置，并可引诱它。',
 'No wild Pokemon, or only stronger ones, until the game is reset.': '关闭野生遭遇，或仅遇到更强的宝可梦；重置游戏后失效。',
 'Legendaries you beat without catching come back.': '被击败但未捕获的传说宝可梦重新出现。',
 'Hatches the eggs you carry, or readies the Day Care egg.': '立即孵化携带的蛋，或让寄放屋准备好蛋。',
 '100,000 money, 99 Rare Candies and 1,000 coins.': '获得 100,000 金钱、99 个神奇糖果和 1,000 枚代币。',
 'Play the slot machines from the delivery man.': '通过配送员玩老虎机。',
 'The party gets the seven event ribbons.': '为队伍添加七种活动奖章。',
 'The delivery man tells your Trainer ID and Secret ID.': '由配送员告知训练家 ID 和里 ID。',
 'Rename yourself, or switch between boy and girl.': '更改自己的姓名，或切换男孩／女孩外观。',
 'Gives your rival a new name.': '为劲敌设置新姓名。',
 'The Colosseum Bonus Disc Jirachi, level 5.': '竞技场奖励光盘的基拉祈，等级 5。',
 'The Pokemon Channel Jirachi, level 5.': 'Pokémon Channel 的基拉祈，等级 5。',
 'The Aura Mew, level 10.': 'Aura 梦幻，等级 10。',
 'The MYSTRY Mew, level 10.': 'MYSTRY 梦幻，等级 10。',
 'The DOEL Deoxys, level 70.': 'DOEL 代欧奇希斯，等级 70。',
 'The SPACE C Deoxys, level 70.': 'SPACE C 代欧奇希斯，等级 70。',
 'The ROCKS Metang, level 30, with the National Ribbon.': 'ROCKS 金属怪，等级 30，附带国家奖章。',
 'Level 70, from the 10th anniversary.': '十周年活动，等级 70。',
 'A Swablu, Zigzagoon, Skitty or Pichu egg with a special move.': '拥有特殊招式的青绵鸟、蛇纹熊、向尾喵或皮丘的蛋。',
 'The Japanese Colosseum bonus disc Pikachu. Its Japanese trainer name shows as dots.': '日版竞技场奖励光盘的皮卡丘，日文训练家姓名显示为圆点。',
 'The Japanese Colosseum bonus disc Celebi. Its Japanese trainer name shows as dots.': '日版竞技场奖励光盘的时拉比，日文训练家姓名显示为圆点。',
 'The Ho-Oh Colosseum gave for 100 Mt. Battle wins.': '竞技场战胜对战山 100 场后赠送的凤王。',
 'A short news; the man in Cerulean City hands over a berry.': '简短新闻；华蓝市的男子会赠送一颗树果。',
 'A long news that scrolls, with a berry.': '可滚动的长新闻，附带一颗树果。',
 'After the card is saved, talk to the delivery man on 2F of any Pokemon Center.': '保存卡片后，与任意宝可梦中心二楼的配送员对话。',
 'Receive it through Mystery Gift, then read the results in the Session log. Your save and Wonder Card are kept.': '通过神秘礼物接收后，在会话日志中查看结果。保留存档和神奇卡片。',
 'Send after saving your boosts. Talk to Mom in Pallet Town to restore them after each restart. Another Wonder Card replaces this gift.': '保存增强功能后发送。每次重启后，与真新镇家中的妈妈对话即可恢复。接收其他神奇卡片会替换此礼物。',
 'First send boosts saved in your game, using Save boosts for later when available. Then send this gift. After each restart, talk to Mom at home in Pallet Town to turn the boosts back on. Send this gift again if you receive another Wonder Card.': '先发送保存到存档中的增强功能；可用时启用“保存增强功能供以后使用”。再发送此礼物。重启后与真新镇家中的妈妈对话恢复；接收其他神奇卡片后需重新发送此礼物。',
 "Shows both IDs in the Session log: your Trainer Card's ID and the normally hidden Secret ID.": '在会话日志中显示训练家卡片上的 '
                                                                                                 'ID 和通常隐藏的里 ID。',
 'Shows your name, Trainer ID (TID), Secret ID (SID) and play time in the Session log. Saves a copy of the read data in Received.': '在会话日志中显示姓名、训练家 '
                                                                                                                                    'ID（TID）、里 '
                                                                                                                                    'ID（SID）和游戏时间；读取的数据另存到接收文件夹。',
 'Shows each Pokemon in your last saved party: nature, six IVs (0-31) and EVs in the Session log. Saves a copy of the read data in Received.': '在会话日志中显示最后保存的队伍中每只宝可梦的性格、六项个体值（0–31）和努力值；数据另存到接收文件夹。',
 'x2, x3 or x4 in the overworld and in battle, and faster text.': '地图和对战采用两倍、三倍或四倍速，并加快文字显示。',
 'Hold a button to walk through walls, trees and water.': '按住按钮可穿过墙壁、树木和水面。',
 'No grass, water or roaming encounters.': '关闭草丛、水面和游走遭遇。',
 'Counts down to the next shiny in the grass.': '显示下次草丛异色遭遇的倒计时。',
 "The lead Pokemon's IVs and nature, top right.": '在右上角显示队首宝可梦的个体值和性格。',
 'Your lead Pokemon walks behind you.': '队首宝可梦跟随在身后。',
 'Select boosts to run together. Save them for Mom to restore after a restart.': '选择同时运行的增强功能。保存后可由妈妈在重启后恢复。',
 'Text prints faster': '加快文字显示',
 'Counts down to the next shiny wild Pokemon in the grass, top right of the screen': '在右上角显示下次草丛野生异色宝可梦的倒计时',
 'No grass, water or roaming encounters; fishing and Sweet Scent still work': '关闭草丛、水面和游走遭遇；仍可钓鱼或使用甜甜香气',
 "The lead Pokemon's six IVs and its nature, top right of the overworld": '在地图右上角显示队首宝可梦的六项个体值和性格',
 'The lead Pokemon walks behind you, hops ledges with you, and smiles and cries when you face it and press A': '队首宝可梦跟随并一起跳下台阶；面向它按 '
                                                                                                               'A '
                                                                                                               '可互动',
 'These boosts stop when you restart the game or turn off the console.': '重启游戏或关闭游戏机后，这些增强功能停止。',
 'Tick at least one boost.': '请至少选择一个增强功能。',
 'The Pokemon follower runs alone: untick the other boosts.': '宝可梦跟随只能单独运行，请取消其他增强功能。',
 'Speed up the game: pick a speed above x1 or faster text.': '加速游戏：请选择高于一倍速的速度，或启用加速文字。',
 'Send Pokemon, items or game boosts, or read your trainer IDs and party stats through Mystery Gift.': '通过神秘礼物发送宝可梦、道具和游戏增强功能，或读取训练家 '
                                                                                                       'ID 与队伍能力。',
 'Send a local wireless gift: choose a preset, an official event, or build your own.': '通过本地无线通信发送礼物：选择预设、官方活动或自行制作。',
 "Find your console's trade search and connect automatically.": '搜索游戏机的交换连接并自动连接。',
 'For boosts, save readouts or your own console code, keep the app running until the Session log shows the result.': '发送增强功能、读取存档或运行自定义游戏机代码时，请保持应用运行直到会话日志显示结果。',
 'Pick on the trade box and confirm once POKELDN appears. Queued Pokemon follow, one per trade.': '看到 POKELDN '
                                                                                                  '后在交换盒子中选择并确认。队列中的宝可梦依次交换，每次一只。',
 'Three Master Balls': '三个大师球',
 '10 Battle Points': '10 对战点数',
 'Pikachu egg': '皮卡丘的蛋',
 'A level 25 Pikachu nicknamed POKELDN.': '等级 25、昵称为 POKELDN 的皮卡丘。',
 'An egg that hatches into Pikachu.': '可孵化出皮卡丘的蛋。',
 'Three Master Balls in the bag.': '向背包添加三个大师球。',
 "Adds 10 BP, up to the game's 9999.": '增加 10 对战点数，上限为 9999。',
 'Fixed Behavior Static Encounter': '固定行为定点遭遇',
 'Static Encounter': '定点遭遇',
 'Wild Encounter': '野生遭遇',
 'In-game Trade': '游戏内交换',
 'Shown on the Wonder News screen as soon as it is received.': '接收后立即显示在神奇新闻画面。',
 'Runs on the console while it receives, inside the Mystery Gift menu.': '接收时在游戏机的神秘礼物菜单中运行。',
 'Your ARM code, checked offline before it is sent': '发送前离线检查自定义 ARM 代码',
 'Received once per save': '每个存档只能领取一次',
 'The player can pass the card on': '玩家可以分享卡片',
 'Listed under Mystery Gift; the player picks it, then it lands in the save.': '在神秘礼物中列出，玩家选择后保存到存档。',
 'The player is its original trainer': '原始训练家为玩家',
 'Sword only: the other version skips the card': '仅限剑：盾会忽略此卡片',
 'Shield only: the other version skips the card': '仅限盾：剑会忽略此卡片',
 'Pokemon species': '宝可梦种类',
 "A game boost is a change to how your game plays, such as walking through walls or a faster game. Select the boosts and send them through Mystery Gift. They start immediately and stop when you restart the game or turn off the console. To restore them later, save them in the game and send Mom's gift below.": '增强功能可改变游戏玩法，例如穿墙或加速。选择功能并通过神秘礼物发送，接收后立即生效，重启游戏或关闭游戏机后停止。若要以后恢复，请将功能保存到存档，并发送下方的妈妈礼物。',
 "Read your Trainer ID (TID), Secret ID (SID), or your party's stats in the Session log. The TID appears on your Trainer Card; the SID is normally hidden. IVs are a Pokemon's six individual stat values, from 0 to 31. EVs are stat points gained through training. These tools keep your save and Wonder Card unchanged.": '在会话日志中读取训练家 '
                                                                                                                                                                                                                                                                                                                              'ID（TID）、里 '
                                                                                                                                                                                                                                                                                                                              'ID（SID）或队伍能力。TID '
                                                                                                                                                                                                                                                                                                                              '显示在训练家卡片上，SID '
                                                                                                                                                                                                                                                                                                                              '通常隐藏。个体值是宝可梦的六项先天能力数值，范围为 '
                                                                                                                                                                                                                                                                                                                              '0–31；努力值通过训练获得。不会修改存档和神奇卡片。',
 'Keep a copy of these boosts in your save. ': '将这些增强功能的副本保存在存档中。',
 'These boosts are saved in your game. ': '这些增强功能已保存在存档中。',
 'Home': '首页',
 'Hardware and setup': '硬件与设置',
 'Adapters': '适配器',
 'ESP32 radio': 'ESP32 无线通信',
 'Raspberry Pi host': '树莓派主机',
 'Switch keys on the Pi': '树莓派上的 Switch 密钥',
 'Desktop builds': '桌面应用',
 'The wireless layer': '无线通信层',
 'The Pia layer': 'Pia 层',
 'Code organization': '代码结构',
 'Host implementation': '主机实现',
 'The ROM map': 'ROM 映射',
 'Code on the console': '游戏机代码',
 'The link protocol': '连接协议',
 'The random number generator': '随机数生成器',
 'Joining and the Pia layer': '加入流程与 Pia 层',
 'The game protocol': '游戏协议',
 'The Union Room trade': '联盟房间交换',
 'The sync framework': '同步框架',
 'The cartridge and the session': '卡带与会话',
 "The Let's Go cartridge and session": "Let's Go 卡带与会话",
 'The Mystery Gift menu': '神秘礼物菜单',
 'The Link Trade': '连接交换',
 'Reverse-engineering a Switch title': 'Switch 游戏逆向分析',
 'Mystery Gift files': '神秘礼物文件',
 'FireRed and LeafGreen': '火红／叶绿',
 "Let's Go Pikachu and Eevee": "Let's Go! 皮卡丘／伊布",
 'Brilliant Diamond and Shining Pearl': '晶灿钻石／明亮珍珠',
 'Scarlet and Violet': '朱／紫',
 'Pick three Pokemon for the link code.': '请选择三只宝可梦作为连接密码。',
 'Build the Pokemon to offer first.': '请先生成用于交换的宝可梦。',
 'The Pokemon is not legal.': '此宝可梦不合法。',
 'This species is absent from the selected game.': '所选游戏中不存在此种类。',
 'This form is absent from the selected game.': '所选游戏中不存在此形态。',
 'This species or form is absent from the selected game.': '所选游戏中不存在此种类或形态。',
 'The Pokemon checksum is invalid.': '宝可梦校验和无效。',
 'The first line names no Pokemon.': '第一行未指定宝可梦。',
 'The text holds no Pokemon set.': '文本中没有宝可梦配置。',
 'Legends Z-A has no abilities; the ability was left out.': '传说 Z-A 不使用特性，已忽略特性设置。',
 'This game has no EVs; the EVs were left out.': '此游戏不使用努力值，已忽略努力值设置。',
 'The Tera Type is not set; the Pokemon keeps its own.': '未设置太晶属性，保留宝可梦原有的属性。',
 'Gigantamax and Dynamax level are not set.': '未设置超极巨化和极巨化等级。',
 'Hidden Power follows the IVs; its type is not set.': '觉醒力量由个体值决定，未单独设置属性。',
 'Friendship is not set.': '未设置亲密度。'}

SPECIES = {'Bulbasaur': '妙蛙种子',
 'Ivysaur': '妙蛙草',
 'Venusaur': '妙蛙花',
 'Charmander': '小火龙',
 'Charmeleon': '火恐龙',
 'Charizard': '喷火龙',
 'Squirtle': '杰尼龟',
 'Wartortle': '卡咪龟',
 'Blastoise': '水箭龟',
 'Caterpie': '绿毛虫',
 'Metapod': '铁甲蛹',
 'Butterfree': '巴大蝶',
 'Weedle': '独角虫',
 'Kakuna': '铁壳蛹',
 'Beedrill': '大针蜂',
 'Pidgey': '波波',
 'Pidgeotto': '比比鸟',
 'Pidgeot': '大比鸟',
 'Rattata': '小拉达',
 'Raticate': '拉达',
 'Spearow': '烈雀',
 'Fearow': '大嘴雀',
 'Ekans': '阿柏蛇',
 'Arbok': '阿柏怪',
 'Pikachu': '皮卡丘',
 'Raichu': '雷丘',
 'Sandshrew': '穿山鼠',
 'Sandslash': '穿山王',
 'Nidoran♀': '尼多兰',
 'Nidorina': '尼多娜',
 'Nidoqueen': '尼多后',
 'Nidoran♂': '尼多朗',
 'Nidorino': '尼多力诺',
 'Nidoking': '尼多王',
 'Clefairy': '皮皮',
 'Clefable': '皮可西',
 'Vulpix': '六尾',
 'Ninetales': '九尾',
 'Jigglypuff': '胖丁',
 'Wigglytuff': '胖可丁',
 'Zubat': '超音蝠',
 'Golbat': '大嘴蝠',
 'Oddish': '走路草',
 'Gloom': '臭臭花',
 'Vileplume': '霸王花',
 'Paras': '派拉斯',
 'Parasect': '派拉斯特',
 'Venonat': '毛球',
 'Venomoth': '摩鲁蛾',
 'Diglett': '地鼠',
 'Dugtrio': '三地鼠',
 'Meowth': '喵喵',
 'Persian': '猫老大',
 'Psyduck': '可达鸭',
 'Golduck': '哥达鸭',
 'Mankey': '猴怪',
 'Primeape': '火暴猴',
 'Growlithe': '卡蒂狗',
 'Arcanine': '风速狗',
 'Poliwag': '蚊香蝌蚪',
 'Poliwhirl': '蚊香君',
 'Poliwrath': '蚊香泳士',
 'Abra': '凯西',
 'Kadabra': '勇基拉',
 'Alakazam': '胡地',
 'Machop': '腕力',
 'Machoke': '豪力',
 'Machamp': '怪力',
 'Bellsprout': '喇叭芽',
 'Weepinbell': '口呆花',
 'Victreebel': '大食花',
 'Tentacool': '玛瑙水母',
 'Tentacruel': '毒刺水母',
 'Geodude': '小拳石',
 'Graveler': '隆隆石',
 'Golem': '隆隆岩',
 'Ponyta': '小火马',
 'Rapidash': '烈焰马',
 'Slowpoke': '呆呆兽',
 'Slowbro': '呆壳兽',
 'Magnemite': '小磁怪',
 'Magneton': '三合一磁怪',
 'Farfetch’d': '大葱鸭',
 'Doduo': '嘟嘟',
 'Dodrio': '嘟嘟利',
 'Seel': '小海狮',
 'Dewgong': '白海狮',
 'Grimer': '臭泥',
 'Muk': '臭臭泥',
 'Shellder': '大舌贝',
 'Cloyster': '刺甲贝',
 'Gastly': '鬼斯',
 'Haunter': '鬼斯通',
 'Gengar': '耿鬼',
 'Onix': '大岩蛇',
 'Drowzee': '催眠貘',
 'Hypno': '引梦貘人',
 'Krabby': '大钳蟹',
 'Kingler': '巨钳蟹',
 'Voltorb': '霹雳电球',
 'Electrode': '顽皮雷弹',
 'Exeggcute': '蛋蛋',
 'Exeggutor': '椰蛋树',
 'Cubone': '卡拉卡拉',
 'Marowak': '嘎啦嘎啦',
 'Hitmonlee': '飞腿郎',
 'Hitmonchan': '快拳郎',
 'Lickitung': '大舌头',
 'Koffing': '瓦斯弹',
 'Weezing': '双弹瓦斯',
 'Rhyhorn': '独角犀牛',
 'Rhydon': '钻角犀兽',
 'Chansey': '吉利蛋',
 'Tangela': '蔓藤怪',
 'Kangaskhan': '袋兽',
 'Horsea': '墨海马',
 'Seadra': '海刺龙',
 'Goldeen': '角金鱼',
 'Seaking': '金鱼王',
 'Staryu': '海星星',
 'Starmie': '宝石海星',
 'Mr. Mime': '魔墙人偶',
 'Scyther': '飞天螳螂',
 'Jynx': '迷唇姐',
 'Electabuzz': '电击兽',
 'Magmar': '鸭嘴火兽',
 'Pinsir': '凯罗斯',
 'Tauros': '肯泰罗',
 'Magikarp': '鲤鱼王',
 'Gyarados': '暴鲤龙',
 'Lapras': '拉普拉斯',
 'Ditto': '百变怪',
 'Eevee': '伊布',
 'Vaporeon': '水伊布',
 'Jolteon': '雷伊布',
 'Flareon': '火伊布',
 'Porygon': '多边兽',
 'Omanyte': '菊石兽',
 'Omastar': '多刺菊石兽',
 'Kabuto': '化石盔',
 'Kabutops': '镰刀盔',
 'Aerodactyl': '化石翼龙',
 'Snorlax': '卡比兽',
 'Articuno': '急冻鸟',
 'Zapdos': '闪电鸟',
 'Moltres': '火焰鸟',
 'Dratini': '迷你龙',
 'Dragonair': '哈克龙',
 'Dragonite': '快龙',
 'Mewtwo': '超梦',
 'Mew': '梦幻',
 'Chikorita': '菊草叶',
 'Bayleef': '月桂叶',
 'Meganium': '大竺葵',
 'Cyndaquil': '火球鼠',
 'Quilava': '火岩鼠',
 'Typhlosion': '火暴兽',
 'Totodile': '小锯鳄',
 'Croconaw': '蓝鳄',
 'Feraligatr': '大力鳄',
 'Sentret': '尾立',
 'Furret': '大尾立',
 'Hoothoot': '咕咕',
 'Noctowl': '猫头夜鹰',
 'Ledyba': '芭瓢虫',
 'Ledian': '安瓢虫',
 'Spinarak': '圆丝蛛',
 'Ariados': '阿利多斯',
 'Crobat': '叉字蝠',
 'Chinchou': '灯笼鱼',
 'Lanturn': '电灯怪',
 'Pichu': '皮丘',
 'Cleffa': '皮宝宝',
 'Igglybuff': '宝宝丁',
 'Togepi': '波克比',
 'Togetic': '波克基古',
 'Natu': '天然雀',
 'Xatu': '天然鸟',
 'Mareep': '咩利羊',
 'Flaaffy': '茸茸羊',
 'Ampharos': '电龙',
 'Bellossom': '美丽花',
 'Marill': '玛力露',
 'Azumarill': '玛力露丽',
 'Sudowoodo': '树才怪',
 'Politoed': '蚊香蛙皇',
 'Hoppip': '毽子草',
 'Skiploom': '毽子花',
 'Jumpluff': '毽子棉',
 'Aipom': '长尾怪手',
 'Sunkern': '向日种子',
 'Sunflora': '向日花怪',
 'Yanma': '蜻蜻蜓',
 'Wooper': '乌波',
 'Quagsire': '沼王',
 'Espeon': '太阳伊布',
 'Umbreon': '月亮伊布',
 'Murkrow': '黑暗鸦',
 'Slowking': '呆呆王',
 'Misdreavus': '梦妖',
 'Unown': '未知图腾',
 'Wobbuffet': '果然翁',
 'Girafarig': '麒麟奇',
 'Pineco': '榛果球',
 'Forretress': '佛烈托斯',
 'Dunsparce': '土龙弟弟',
 'Gligar': '天蝎',
 'Steelix': '大钢蛇',
 'Snubbull': '布鲁',
 'Granbull': '布鲁皇',
 'Qwilfish': '千针鱼',
 'Scizor': '巨钳螳螂',
 'Shuckle': '壶壶',
 'Heracross': '赫拉克罗斯',
 'Sneasel': '狃拉',
 'Teddiursa': '熊宝宝',
 'Ursaring': '圈圈熊',
 'Slugma': '熔岩虫',
 'Magcargo': '熔岩蜗牛',
 'Swinub': '小山猪',
 'Piloswine': '长毛猪',
 'Corsola': '太阳珊瑚',
 'Remoraid': '铁炮鱼',
 'Octillery': '章鱼桶',
 'Delibird': '信使鸟',
 'Mantine': '巨翅飞鱼',
 'Skarmory': '盔甲鸟',
 'Houndour': '戴鲁比',
 'Houndoom': '黑鲁加',
 'Kingdra': '刺龙王',
 'Phanpy': '小小象',
 'Donphan': '顿甲',
 'Porygon2': '多边兽２型',
 'Stantler': '惊角鹿',
 'Smeargle': '图图犬',
 'Tyrogue': '无畏小子',
 'Hitmontop': '战舞郎',
 'Smoochum': '迷唇娃',
 'Elekid': '电击怪',
 'Magby': '鸭嘴宝宝',
 'Miltank': '大奶罐',
 'Blissey': '幸福蛋',
 'Raikou': '雷公',
 'Entei': '炎帝',
 'Suicune': '水君',
 'Larvitar': '幼基拉斯',
 'Pupitar': '沙基拉斯',
 'Tyranitar': '班基拉斯',
 'Lugia': '洛奇亚',
 'Ho-Oh': '凤王',
 'Celebi': '时拉比',
 'Treecko': '木守宫',
 'Grovyle': '森林蜥蜴',
 'Sceptile': '蜥蜴王',
 'Torchic': '火稚鸡',
 'Combusken': '力壮鸡',
 'Blaziken': '火焰鸡',
 'Mudkip': '水跃鱼',
 'Marshtomp': '沼跃鱼',
 'Swampert': '巨沼怪',
 'Poochyena': '土狼犬',
 'Mightyena': '大狼犬',
 'Zigzagoon': '蛇纹熊',
 'Linoone': '直冲熊',
 'Wurmple': '刺尾虫',
 'Silcoon': '甲壳茧',
 'Beautifly': '狩猎凤蝶',
 'Cascoon': '盾甲茧',
 'Dustox': '毒粉蛾',
 'Lotad': '莲叶童子',
 'Lombre': '莲帽小童',
 'Ludicolo': '乐天河童',
 'Seedot': '橡实果',
 'Nuzleaf': '长鼻叶',
 'Shiftry': '狡猾天狗',
 'Taillow': '傲骨燕',
 'Swellow': '大王燕',
 'Wingull': '长翅鸥',
 'Pelipper': '大嘴鸥',
 'Ralts': '拉鲁拉丝',
 'Kirlia': '奇鲁莉安',
 'Gardevoir': '沙奈朵',
 'Surskit': '溜溜糖球',
 'Masquerain': '雨翅蛾',
 'Shroomish': '蘑蘑菇',
 'Breloom': '斗笠菇',
 'Slakoth': '懒人獭',
 'Vigoroth': '过动猿',
 'Slaking': '请假王',
 'Nincada': '土居忍士',
 'Ninjask': '铁面忍者',
 'Shedinja': '脱壳忍者',
 'Whismur': '咕妞妞',
 'Loudred': '吼爆弹',
 'Exploud': '爆音怪',
 'Makuhita': '幕下力士',
 'Hariyama': '铁掌力士',
 'Azurill': '露力丽',
 'Nosepass': '朝北鼻',
 'Skitty': '向尾喵',
 'Delcatty': '优雅猫',
 'Sableye': '勾魂眼',
 'Mawile': '大嘴娃',
 'Aron': '可可多拉',
 'Lairon': '可多拉',
 'Aggron': '波士可多拉',
 'Meditite': '玛沙那',
 'Medicham': '恰雷姆',
 'Electrike': '落雷兽',
 'Manectric': '雷电兽',
 'Plusle': '正电拍拍',
 'Minun': '负电拍拍',
 'Volbeat': '电萤虫',
 'Illumise': '甜甜萤',
 'Roselia': '毒蔷薇',
 'Gulpin': '溶食兽',
 'Swalot': '吞食兽',
 'Carvanha': '利牙鱼',
 'Sharpedo': '巨牙鲨',
 'Wailmer': '吼吼鲸',
 'Wailord': '吼鲸王',
 'Numel': '呆火驼',
 'Camerupt': '喷火驼',
 'Torkoal': '煤炭龟',
 'Spoink': '跳跳猪',
 'Grumpig': '噗噗猪',
 'Spinda': '晃晃斑',
 'Trapinch': '大颚蚁',
 'Vibrava': '超音波幼虫',
 'Flygon': '沙漠蜻蜓',
 'Cacnea': '刺球仙人掌',
 'Cacturne': '梦歌仙人掌',
 'Swablu': '青绵鸟',
 'Altaria': '七夕青鸟',
 'Zangoose': '猫鼬斩',
 'Seviper': '饭匙蛇',
 'Lunatone': '月石',
 'Solrock': '太阳岩',
 'Barboach': '泥泥鳅',
 'Whiscash': '鲶鱼王',
 'Corphish': '龙虾小兵',
 'Crawdaunt': '铁螯龙虾',
 'Baltoy': '天秤偶',
 'Claydol': '念力土偶',
 'Lileep': '触手百合',
 'Cradily': '摇篮百合',
 'Anorith': '太古羽虫',
 'Armaldo': '太古盔甲',
 'Feebas': '丑丑鱼',
 'Milotic': '美纳斯',
 'Castform': '飘浮泡泡',
 'Kecleon': '变隐龙',
 'Shuppet': '怨影娃娃',
 'Banette': '诅咒娃娃',
 'Duskull': '夜巡灵',
 'Dusclops': '彷徨夜灵',
 'Tropius': '热带龙',
 'Chimecho': '风铃铃',
 'Absol': '阿勃梭鲁',
 'Wynaut': '小果然',
 'Snorunt': '雪童子',
 'Glalie': '冰鬼护',
 'Spheal': '海豹球',
 'Sealeo': '海魔狮',
 'Walrein': '帝牙海狮',
 'Clamperl': '珍珠贝',
 'Huntail': '猎斑鱼',
 'Gorebyss': '樱花鱼',
 'Relicanth': '古空棘鱼',
 'Luvdisc': '爱心鱼',
 'Bagon': '宝贝龙',
 'Shelgon': '甲壳龙',
 'Salamence': '暴飞龙',
 'Beldum': '铁哑铃',
 'Metang': '金属怪',
 'Metagross': '巨金怪',
 'Regirock': '雷吉洛克',
 'Regice': '雷吉艾斯',
 'Registeel': '雷吉斯奇鲁',
 'Latias': '拉帝亚斯',
 'Latios': '拉帝欧斯',
 'Kyogre': '盖欧卡',
 'Groudon': '固拉多',
 'Rayquaza': '烈空坐',
 'Jirachi': '基拉祈',
 'Deoxys': '代欧奇希斯',
 'Turtwig': '草苗龟',
 'Grotle': '树林龟',
 'Torterra': '土台龟',
 'Chimchar': '小火焰猴',
 'Monferno': '猛火猴',
 'Infernape': '烈焰猴',
 'Piplup': '波加曼',
 'Prinplup': '波皇子',
 'Empoleon': '帝王拿波',
 'Starly': '姆克儿',
 'Staravia': '姆克鸟',
 'Staraptor': '姆克鹰',
 'Bidoof': '大牙狸',
 'Bibarel': '大尾狸',
 'Kricketot': '圆法师',
 'Kricketune': '音箱蟀',
 'Shinx': '小猫怪',
 'Luxio': '勒克猫',
 'Luxray': '伦琴猫',
 'Budew': '含羞苞',
 'Roserade': '罗丝雷朵',
 'Cranidos': '头盖龙',
 'Rampardos': '战槌龙',
 'Shieldon': '盾甲龙',
 'Bastiodon': '护城龙',
 'Burmy': '结草儿',
 'Wormadam': '结草贵妇',
 'Mothim': '绅士蛾',
 'Combee': '三蜜蜂',
 'Vespiquen': '蜂女王',
 'Pachirisu': '帕奇利兹',
 'Buizel': '泳圈鼬',
 'Floatzel': '浮潜鼬',
 'Cherubi': '樱花宝',
 'Cherrim': '樱花儿',
 'Shellos': '无壳海兔',
 'Gastrodon': '海兔兽',
 'Ambipom': '双尾怪手',
 'Drifloon': '飘飘球',
 'Drifblim': '随风球',
 'Buneary': '卷卷耳',
 'Lopunny': '长耳兔',
 'Mismagius': '梦妖魔',
 'Honchkrow': '乌鸦头头',
 'Glameow': '魅力喵',
 'Purugly': '东施喵',
 'Chingling': '铃铛响',
 'Stunky': '臭鼬噗',
 'Skuntank': '坦克臭鼬',
 'Bronzor': '铜镜怪',
 'Bronzong': '青铜钟',
 'Bonsly': '盆才怪',
 'Mime Jr.': '魔尼尼',
 'Happiny': '小福蛋',
 'Chatot': '聒噪鸟',
 'Spiritomb': '花岩怪',
 'Gible': '圆陆鲨',
 'Gabite': '尖牙陆鲨',
 'Garchomp': '烈咬陆鲨',
 'Munchlax': '小卡比兽',
 'Riolu': '利欧路',
 'Lucario': '路卡利欧',
 'Hippopotas': '沙河马',
 'Hippowdon': '河马兽',
 'Skorupi': '钳尾蝎',
 'Drapion': '龙王蝎',
 'Croagunk': '不良蛙',
 'Toxicroak': '毒骷蛙',
 'Carnivine': '尖牙笼',
 'Finneon': '荧光鱼',
 'Lumineon': '霓虹鱼',
 'Mantyke': '小球飞鱼',
 'Snover': '雪笠怪',
 'Abomasnow': '暴雪王',
 'Weavile': '玛狃拉',
 'Magnezone': '自爆磁怪',
 'Lickilicky': '大舌舔',
 'Rhyperior': '超甲狂犀',
 'Tangrowth': '巨蔓藤',
 'Electivire': '电击魔兽',
 'Magmortar': '鸭嘴炎兽',
 'Togekiss': '波克基斯',
 'Yanmega': '远古巨蜓',
 'Leafeon': '叶伊布',
 'Glaceon': '冰伊布',
 'Gliscor': '天蝎王',
 'Mamoswine': '象牙猪',
 'Porygon-Z': '多边兽乙型',
 'Gallade': '艾路雷朵',
 'Probopass': '大朝北鼻',
 'Dusknoir': '黑夜魔灵',
 'Froslass': '雪妖女',
 'Rotom': '洛托姆',
 'Uxie': '由克希',
 'Mesprit': '艾姆利多',
 'Azelf': '亚克诺姆',
 'Dialga': '帝牙卢卡',
 'Palkia': '帕路奇亚',
 'Heatran': '席多蓝恩',
 'Regigigas': '雷吉奇卡斯',
 'Giratina': '骑拉帝纳',
 'Cresselia': '克雷色利亚',
 'Phione': '霏欧纳',
 'Manaphy': '玛纳霏',
 'Darkrai': '达克莱伊',
 'Shaymin': '谢米',
 'Arceus': '阿尔宙斯',
 'Victini': '比克提尼',
 'Snivy': '藤藤蛇',
 'Servine': '青藤蛇',
 'Serperior': '君主蛇',
 'Tepig': '暖暖猪',
 'Pignite': '炒炒猪',
 'Emboar': '炎武王',
 'Oshawott': '水水獭',
 'Dewott': '双刃丸',
 'Samurott': '大剑鬼',
 'Patrat': '探探鼠',
 'Watchog': '步哨鼠',
 'Lillipup': '小约克',
 'Herdier': '哈约克',
 'Stoutland': '长毛狗',
 'Purrloin': '扒手猫',
 'Liepard': '酷豹',
 'Pansage': '花椰猴',
 'Simisage': '花椰猿',
 'Pansear': '爆香猴',
 'Simisear': '爆香猿',
 'Panpour': '冷水猴',
 'Simipour': '冷水猿',
 'Munna': '食梦梦',
 'Musharna': '梦梦蚀',
 'Pidove': '豆豆鸽',
 'Tranquill': '咕咕鸽',
 'Unfezant': '高傲雉鸡',
 'Blitzle': '斑斑马',
 'Zebstrika': '雷电斑马',
 'Roggenrola': '石丸子',
 'Boldore': '地幔岩',
 'Gigalith': '庞岩怪',
 'Woobat': '滚滚蝙蝠',
 'Swoobat': '心蝙蝠',
 'Drilbur': '螺钉地鼠',
 'Excadrill': '龙头地鼠',
 'Audino': '差不多娃娃',
 'Timburr': '搬运小匠',
 'Gurdurr': '铁骨土人',
 'Conkeldurr': '修建老匠',
 'Tympole': '圆蝌蚪',
 'Palpitoad': '蓝蟾蜍',
 'Seismitoad': '蟾蜍王',
 'Throh': '投摔鬼',
 'Sawk': '打击鬼',
 'Sewaddle': '虫宝包',
 'Swadloon': '宝包茧',
 'Leavanny': '保姆虫',
 'Venipede': '百足蜈蚣',
 'Whirlipede': '车轮球',
 'Scolipede': '蜈蚣王',
 'Cottonee': '木棉球',
 'Whimsicott': '风妖精',
 'Petilil': '百合根娃娃',
 'Lilligant': '裙儿小姐',
 'Basculin': '野蛮鲈鱼',
 'Sandile': '黑眼鳄',
 'Krokorok': '混混鳄',
 'Krookodile': '流氓鳄',
 'Darumaka': '火红不倒翁',
 'Darmanitan': '达摩狒狒',
 'Maractus': '沙铃仙人掌',
 'Dwebble': '石居蟹',
 'Crustle': '岩殿居蟹',
 'Scraggy': '滑滑小子',
 'Scrafty': '头巾混混',
 'Sigilyph': '象征鸟',
 'Yamask': '哭哭面具',
 'Cofagrigus': '迭失棺',
 'Tirtouga': '原盖海龟',
 'Carracosta': '肋骨海龟',
 'Archen': '始祖小鸟',
 'Archeops': '始祖大鸟',
 'Trubbish': '破破袋',
 'Garbodor': '灰尘山',
 'Zorua': '索罗亚',
 'Zoroark': '索罗亚克',
 'Minccino': '泡沫栗鼠',
 'Cinccino': '奇诺栗鼠',
 'Gothita': '哥德宝宝',
 'Gothorita': '哥德小童',
 'Gothitelle': '哥德小姐',
 'Solosis': '单卵细胞球',
 'Duosion': '双卵细胞球',
 'Reuniclus': '人造细胞卵',
 'Ducklett': '鸭宝宝',
 'Swanna': '舞天鹅',
 'Vanillite': '迷你冰',
 'Vanillish': '多多冰',
 'Vanilluxe': '双倍多多冰',
 'Deerling': '四季鹿',
 'Sawsbuck': '萌芽鹿',
 'Emolga': '电飞鼠',
 'Karrablast': '盖盖虫',
 'Escavalier': '骑士蜗牛',
 'Foongus': '哎呀球菇',
 'Amoonguss': '败露球菇',
 'Frillish': '轻飘飘',
 'Jellicent': '胖嘟嘟',
 'Alomomola': '保姆曼波',
 'Joltik': '电电虫',
 'Galvantula': '电蜘蛛',
 'Ferroseed': '种子铁球',
 'Ferrothorn': '坚果哑铃',
 'Klink': '齿轮儿',
 'Klang': '齿轮组',
 'Klinklang': '齿轮怪',
 'Tynamo': '麻麻小鱼',
 'Eelektrik': '麻麻鳗',
 'Eelektross': '麻麻鳗鱼王',
 'Elgyem': '小灰怪',
 'Beheeyem': '大宇怪',
 'Litwick': '烛光灵',
 'Lampent': '灯火幽灵',
 'Chandelure': '水晶灯火灵',
 'Axew': '牙牙',
 'Fraxure': '斧牙龙',
 'Haxorus': '双斧战龙',
 'Cubchoo': '喷嚏熊',
 'Beartic': '冻原熊',
 'Cryogonal': '几何雪花',
 'Shelmet': '小嘴蜗',
 'Accelgor': '敏捷虫',
 'Stunfisk': '泥巴鱼',
 'Mienfoo': '功夫鼬',
 'Mienshao': '师父鼬',
 'Druddigon': '赤面龙',
 'Golett': '泥偶小人',
 'Golurk': '泥偶巨人',
 'Pawniard': '驹刀小兵',
 'Bisharp': '劈斩司令',
 'Bouffalant': '爆炸头水牛',
 'Rufflet': '毛头小鹰',
 'Braviary': '勇士雄鹰',
 'Vullaby': '秃鹰丫头',
 'Mandibuzz': '秃鹰娜',
 'Heatmor': '熔蚁兽',
 'Durant': '铁蚁',
 'Deino': '单首龙',
 'Zweilous': '双首暴龙',
 'Hydreigon': '三首恶龙',
 'Larvesta': '燃烧虫',
 'Volcarona': '火神蛾',
 'Cobalion': '勾帕路翁',
 'Terrakion': '代拉基翁',
 'Virizion': '毕力吉翁',
 'Tornadus': '龙卷云',
 'Thundurus': '雷电云',
 'Reshiram': '莱希拉姆',
 'Zekrom': '捷克罗姆',
 'Landorus': '土地云',
 'Kyurem': '酋雷姆',
 'Keldeo': '凯路迪欧',
 'Meloetta': '美洛耶塔',
 'Genesect': '盖诺赛克特',
 'Chespin': '哈力栗',
 'Quilladin': '胖胖哈力',
 'Chesnaught': '布里卡隆',
 'Fennekin': '火狐狸',
 'Braixen': '长尾火狐',
 'Delphox': '妖火红狐',
 'Froakie': '呱呱泡蛙',
 'Frogadier': '呱头蛙',
 'Greninja': '甲贺忍蛙',
 'Bunnelby': '掘掘兔',
 'Diggersby': '掘地兔',
 'Fletchling': '小箭雀',
 'Fletchinder': '火箭雀',
 'Talonflame': '烈箭鹰',
 'Scatterbug': '粉蝶虫',
 'Spewpa': '粉蝶蛹',
 'Vivillon': '彩粉蝶',
 'Litleo': '小狮狮',
 'Pyroar': '火炎狮',
 'Flabébé': '花蓓蓓',
 'Floette': '花叶蒂',
 'Florges': '花洁夫人',
 'Skiddo': '坐骑小羊',
 'Gogoat': '坐骑山羊',
 'Pancham': '顽皮熊猫',
 'Pangoro': '霸道熊猫',
 'Furfrou': '多丽米亚',
 'Espurr': '妙喵',
 'Meowstic': '超能妙喵',
 'Honedge': '独剑鞘',
 'Doublade': '双剑鞘',
 'Aegislash': '坚盾剑怪',
 'Spritzee': '粉香香',
 'Aromatisse': '芳香精',
 'Swirlix': '绵绵泡芙',
 'Slurpuff': '胖甜妮',
 'Inkay': '好啦鱿',
 'Malamar': '乌贼王',
 'Binacle': '龟脚脚',
 'Barbaracle': '龟足巨铠',
 'Skrelp': '垃垃藻',
 'Dragalge': '毒藻龙',
 'Clauncher': '铁臂枪虾',
 'Clawitzer': '钢炮臂虾',
 'Helioptile': '伞电蜥',
 'Heliolisk': '光电伞蜥',
 'Tyrunt': '宝宝暴龙',
 'Tyrantrum': '怪颚龙',
 'Amaura': '冰雪龙',
 'Aurorus': '冰雪巨龙',
 'Sylveon': '仙子伊布',
 'Hawlucha': '摔角鹰人',
 'Dedenne': '咚咚鼠',
 'Carbink': '小碎钻',
 'Goomy': '黏黏宝',
 'Sliggoo': '黏美儿',
 'Goodra': '黏美龙',
 'Klefki': '钥圈儿',
 'Phantump': '小木灵',
 'Trevenant': '朽木妖',
 'Pumpkaboo': '南瓜精',
 'Gourgeist': '南瓜怪人',
 'Bergmite': '冰宝',
 'Avalugg': '冰岩怪',
 'Noibat': '嗡蝠',
 'Noivern': '音波龙',
 'Xerneas': '哲尔尼亚斯',
 'Yveltal': '伊裴尔塔尔',
 'Zygarde': '基格尔德',
 'Diancie': '蒂安希',
 'Hoopa': '胡帕',
 'Volcanion': '波尔凯尼恩',
 'Rowlet': '木木枭',
 'Dartrix': '投羽枭',
 'Decidueye': '狙射树枭',
 'Litten': '火斑喵',
 'Torracat': '炎热喵',
 'Incineroar': '炽焰咆哮虎',
 'Popplio': '球球海狮',
 'Brionne': '花漾海狮',
 'Primarina': '西狮海壬',
 'Pikipek': '小笃儿',
 'Trumbeak': '喇叭啄鸟',
 'Toucannon': '铳嘴大鸟',
 'Yungoos': '猫鼬少',
 'Gumshoos': '猫鼬探长',
 'Grubbin': '强颚鸡母虫',
 'Charjabug': '虫电宝',
 'Vikavolt': '锹农炮虫',
 'Crabrawler': '好胜蟹',
 'Crabominable': '好胜毛蟹',
 'Oricorio': '花舞鸟',
 'Cutiefly': '萌虻',
 'Ribombee': '蝶结萌虻',
 'Rockruff': '岩狗狗',
 'Lycanroc': '鬃岩狼人',
 'Wishiwashi': '弱丁鱼',
 'Mareanie': '好坏星',
 'Toxapex': '超坏星',
 'Mudbray': '泥驴仔',
 'Mudsdale': '重泥挽马',
 'Dewpider': '滴蛛',
 'Araquanid': '滴蛛霸',
 'Fomantis': '伪螳草',
 'Lurantis': '兰螳花',
 'Morelull': '睡睡菇',
 'Shiinotic': '灯罩夜菇',
 'Salandit': '夜盗火蜥',
 'Salazzle': '焰后蜥',
 'Stufful': '童偶熊',
 'Bewear': '穿着熊',
 'Bounsweet': '甜竹竹',
 'Steenee': '甜舞妮',
 'Tsareena': '甜冷美后',
 'Comfey': '花疗环环',
 'Oranguru': '智挥猩',
 'Passimian': '投掷猴',
 'Wimpod': '胆小虫',
 'Golisopod': '具甲武者',
 'Sandygast': '沙丘娃',
 'Palossand': '噬沙堡爷',
 'Pyukumuku': '拳海参',
 'Type: Null': '属性：空',
 'Silvally': '银伴战兽',
 'Minior': '小陨星',
 'Komala': '树枕尾熊',
 'Turtonator': '爆焰龟兽',
 'Togedemaru': '托戈德玛尔',
 'Mimikyu': '谜拟丘',
 'Bruxish': '磨牙彩皮鱼',
 'Drampa': '老翁龙',
 'Dhelmise': '破破舵轮',
 'Jangmo-o': '心鳞宝',
 'Hakamo-o': '鳞甲龙',
 'Kommo-o': '杖尾鳞甲龙',
 'Tapu Koko': '卡璞・鸣鸣',
 'Tapu Lele': '卡璞・蝶蝶',
 'Tapu Bulu': '卡璞・哞哞',
 'Tapu Fini': '卡璞・鳍鳍',
 'Cosmog': '科斯莫古',
 'Cosmoem': '科斯莫姆',
 'Solgaleo': '索尔迦雷欧',
 'Lunala': '露奈雅拉',
 'Nihilego': '虚吾伊德',
 'Buzzwole': '爆肌蚊',
 'Pheromosa': '费洛美螂',
 'Xurkitree': '电束木',
 'Celesteela': '铁火辉夜',
 'Kartana': '纸御剑',
 'Guzzlord': '恶食大王',
 'Necrozma': '奈克洛兹玛',
 'Magearna': '玛机雅娜',
 'Marshadow': '玛夏多',
 'Poipole': '毒贝比',
 'Naganadel': '四颚针龙',
 'Stakataka': '垒磊石',
 'Blacephalon': '砰头小丑',
 'Zeraora': '捷拉奥拉',
 'Meltan': '美录坦',
 'Melmetal': '美录梅塔',
 'Grookey': '敲音猴',
 'Thwackey': '啪咚猴',
 'Rillaboom': '轰擂金刚猩',
 'Scorbunny': '炎兔儿',
 'Raboot': '腾蹴小将',
 'Cinderace': '闪焰王牌',
 'Sobble': '泪眼蜥',
 'Drizzile': '变涩蜥',
 'Inteleon': '千面避役',
 'Skwovet': '贪心栗鼠',
 'Greedent': '藏饱栗鼠',
 'Rookidee': '稚山雀',
 'Corvisquire': '蓝鸦',
 'Corviknight': '钢铠鸦',
 'Blipbug': '索侦虫',
 'Dottler': '天罩虫',
 'Orbeetle': '以欧路普',
 'Nickit': '狡小狐',
 'Thievul': '猾大狐',
 'Gossifleur': '幼棉棉',
 'Eldegoss': '白蓬蓬',
 'Wooloo': '毛辫羊',
 'Dubwool': '毛毛角羊',
 'Chewtle': '咬咬龟',
 'Drednaw': '暴噬龟',
 'Yamper': '来电汪',
 'Boltund': '逐电犬',
 'Rolycoly': '小炭仔',
 'Carkol': '大炭车',
 'Coalossal': '巨炭山',
 'Applin': '啃果虫',
 'Flapple': '苹裹龙',
 'Appletun': '丰蜜龙',
 'Silicobra': '沙包蛇',
 'Sandaconda': '沙螺蟒',
 'Cramorant': '古月鸟',
 'Arrokuda': '刺梭鱼',
 'Barraskewda': '戽斗尖梭',
 'Toxel': '电音婴',
 'Toxtricity': '颤弦蝾螈',
 'Sizzlipede': '烧火蚣',
 'Centiskorch': '焚焰蚣',
 'Clobbopus': '拳拳蛸',
 'Grapploct': '八爪武师',
 'Sinistea': '来悲茶',
 'Polteageist': '怖思壶',
 'Hatenna': '迷布莉姆',
 'Hattrem': '提布莉姆',
 'Hatterene': '布莉姆温',
 'Impidimp': '捣蛋小妖',
 'Morgrem': '诈唬魔',
 'Grimmsnarl': '长毛巨魔',
 'Obstagoon': '堵拦熊',
 'Perrserker': '喵头目',
 'Cursola': '魔灵珊瑚',
 'Sirfetch’d': '葱游兵',
 'Mr. Rime': '踏冰人偶',
 'Runerigus': '迭失板',
 'Milcery': '小仙奶',
 'Alcremie': '霜奶仙',
 'Falinks': '列阵兵',
 'Pincurchin': '啪嚓海胆',
 'Snom': '雪吞虫',
 'Frosmoth': '雪绒蛾',
 'Stonjourner': '巨石丁',
 'Eiscue': '冰砌鹅',
 'Indeedee': '爱管侍',
 'Morpeko': '莫鲁贝可',
 'Cufant': '铜象',
 'Copperajah': '大王铜象',
 'Dracozolt': '雷鸟龙',
 'Arctozolt': '雷鸟海兽',
 'Dracovish': '鳃鱼龙',
 'Arctovish': '鳃鱼海兽',
 'Duraludon': '铝钢龙',
 'Dreepy': '多龙梅西亚',
 'Drakloak': '多龙奇',
 'Dragapult': '多龙巴鲁托',
 'Zacian': '苍响',
 'Zamazenta': '藏玛然特',
 'Eternatus': '无极汰那',
 'Kubfu': '熊徒弟',
 'Urshifu': '武道熊师',
 'Zarude': '萨戮德',
 'Regieleki': '雷吉艾勒奇',
 'Regidrago': '雷吉铎拉戈',
 'Glastrier': '雪暴马',
 'Spectrier': '灵幽马',
 'Calyrex': '蕾冠王',
 'Wyrdeer': '诡角鹿',
 'Kleavor': '劈斧螳螂',
 'Ursaluna': '月月熊',
 'Basculegion': '幽尾玄鱼',
 'Sneasler': '大狃拉',
 'Overqwil': '万针鱼',
 'Enamorus': '眷恋云',
 'Sprigatito': '新叶喵',
 'Floragato': '蒂蕾喵',
 'Meowscarada': '魔幻假面喵',
 'Fuecoco': '呆火鳄',
 'Crocalor': '炙烫鳄',
 'Skeledirge': '骨纹巨声鳄',
 'Quaxly': '润水鸭',
 'Quaxwell': '涌跃鸭',
 'Quaquaval': '狂欢浪舞鸭',
 'Lechonk': '爱吃豚',
 'Oinkologne': '飘香豚',
 'Tarountula': '团珠蛛',
 'Spidops': '操陷蛛',
 'Nymble': '豆蟋蟀',
 'Lokix': '烈腿蝗',
 'Pawmi': '布拨',
 'Pawmo': '布土拨',
 'Pawmot': '巴布土拨',
 'Tandemaus': '一对鼠',
 'Maushold': '一家鼠',
 'Fidough': '狗仔包',
 'Dachsbun': '麻花犬',
 'Smoliv': '迷你芙',
 'Dolliv': '奥利纽',
 'Arboliva': '奥利瓦',
 'Squawkabilly': '怒鹦哥',
 'Nacli': '盐石宝',
 'Naclstack': '盐石垒',
 'Garganacl': '盐石巨灵',
 'Charcadet': '炭小侍',
 'Armarouge': '红莲铠骑',
 'Ceruledge': '苍炎刃鬼',
 'Tadbulb': '光蚪仔',
 'Bellibolt': '电肚蛙',
 'Wattrel': '电海燕',
 'Kilowattrel': '大电海燕',
 'Maschiff': '偶叫獒',
 'Mabosstiff': '獒教父',
 'Shroodle': '滋汁鼹',
 'Grafaiai': '涂标客',
 'Bramblin': '纳噬草',
 'Brambleghast': '怖纳噬草',
 'Toedscool': '原野水母',
 'Toedscruel': '陆地水母',
 'Klawf': '毛崖蟹',
 'Capsakid': '热辣娃',
 'Scovillain': '狠辣椒',
 'Rellor': '虫滚泥',
 'Rabsca': '虫甲圣',
 'Flittle': '飘飘雏',
 'Espathra': '超能艳鸵',
 'Tinkatink': '小锻匠',
 'Tinkatuff': '巧锻匠',
 'Tinkaton': '巨锻匠',
 'Wiglett': '海地鼠',
 'Wugtrio': '三海地鼠',
 'Bombirdier': '下石鸟',
 'Finizen': '波普海豚',
 'Palafin': '海豚侠',
 'Varoom': '噗隆隆',
 'Revavroom': '普隆隆姆',
 'Cyclizar': '摩托蜥',
 'Orthworm': '拖拖蚓',
 'Glimmet': '晶光芽',
 'Glimmora': '晶光花',
 'Greavard': '墓仔狗',
 'Houndstone': '墓扬犬',
 'Flamigo': '缠红鹤',
 'Cetoddle': '走鲸',
 'Cetitan': '浩大鲸',
 'Veluza': '轻身鳕',
 'Dondozo': '吃吼霸',
 'Tatsugiri': '米立龙',
 'Annihilape': '弃世猴',
 'Clodsire': '土王',
 'Farigiraf': '奇麒麟',
 'Dudunsparce': '土龙节节',
 'Kingambit': '仆刀将军',
 'Great Tusk': '雄伟牙',
 'Scream Tail': '吼叫尾',
 'Brute Bonnet': '猛恶菇',
 'Flutter Mane': '振翼发',
 'Slither Wing': '爬地翅',
 'Sandy Shocks': '沙铁皮',
 'Iron Treads': '铁辙迹',
 'Iron Bundle': '铁包袱',
 'Iron Hands': '铁臂膀',
 'Iron Jugulis': '铁脖颈',
 'Iron Moth': '铁毒蛾',
 'Iron Thorns': '铁荆棘',
 'Frigibax': '凉脊龙',
 'Arctibax': '冻脊龙',
 'Baxcalibur': '戟脊龙',
 'Gimmighoul': '索财灵',
 'Gholdengo': '赛富豪',
 'Wo-Chien': '古简蜗',
 'Chien-Pao': '古剑豹',
 'Ting-Lu': '古鼎鹿',
 'Chi-Yu': '古玉鱼',
 'Roaring Moon': '轰鸣月',
 'Iron Valiant': '铁武者',
 'Koraidon': '故勒顿',
 'Miraidon': '密勒顿',
 'Walking Wake': '波荡水',
 'Iron Leaves': '铁斑叶',
 'Dipplin': '裹蜜虫',
 'Poltchageist': '斯魔茶',
 'Sinistcha': '来悲粗茶',
 'Okidogi': '够赞狗',
 'Munkidori': '愿增猿',
 'Fezandipiti': '吉雉鸡',
 'Ogerpon': '厄诡椪',
 'Archaludon': '铝钢桥龙',
 'Hydrapple': '蜜集大蛇',
 'Gouging Fire': '破空焰',
 'Raging Bolt': '猛雷鼓',
 'Iron Boulder': '铁磐岩',
 'Iron Crown': '铁头壳',
 'Terapagos': '太乐巴戈斯',
 'Pecharunt': '桃歹郎'}


# Validation messages surfaced by the desktop app, including less common invalid inputs.
LABELS.update({
    "This version is incompatible with the selected game.": "此版本与所选游戏不兼容。",
    "Level must be between 0 and 100.": "等级必须在 0 到 100 之间。",
    "A WC8 record must contain 720 bytes.": "WC8 记录必须包含 720 字节。",
    "This species or form is absent from Sword/Shield.": "剑／盾中不存在此种类或形态。",
    "This move is unavailable in Sword/Shield.": "剑／盾中无法使用此招式。",
    "Invalid gift level, ball or held item.": "礼物的等级、精灵球或携带物品无效。",
    "Invalid gift gender, nature, ability, shininess or Dynamax level.": "礼物的性别、性格、特性、异色或极巨化等级无效。",
    "This species has no Gigantamax form.": "此种类没有超极巨化形态。",
    "Invalid gift item or quantity; bag items only, up to 999.": "礼物物品或数量无效；仅允许背包物品，数量最多 999。",
    "Invalid clothing category or index.": "服装类别或编号无效。",
    "Money is 1 to 9,999,999.": "金钱数量必须在 1 到 9,999,999 之间。",
    "Supported WC8 gifts are Pokemon, bag items, BP, clothing and money.": "WC8 礼物支持宝可梦、背包物品、对战点数、服装和金钱。",
    "An IV is at most 31 and an effort value at most 252.": "单项个体值最多为 31，努力值最多为 252。",
    "Unknown nature.": "未知性格。",
    "A Pokemon knows at most four moves.": "一只宝可梦最多拥有四个招式。",
    "The assembler failed.": "汇编器执行失败。",
    "The offline check needs Unicorn, which this install lacks.": "离线检查需要 Unicorn，当前安装中缺少此组件。",
    "No published release carries the firmware images": "已发布的版本中没有固件镜像。",
    "unknown error": "未知错误",
})

LABELS.update({
    "Ten Rare Candies": "十颗神奇糖果",
    "Ten Rare Candies in the bag.": "在背包中添加十颗神奇糖果。",
    "Training kit": "训练套装",
    "Rare Candies, Exp. Candy XL, PP Max, an Ability Capsule and Bottle Caps.": "包含神奇糖果、经验糖果 XL、ＰＰ极限提升剂、特性胶囊和王冠。",
    "Pocket money": "零用钱",
    "Adds 100,000 to the player's money.": "为玩家增加 100,000 金钱。",
    "Tracksuit": "运动服",
    "The tracksuit set, in the wardrobe.": "在衣柜中添加运动服套装。",
    "Leon's cap and tights": "丹帝的帽子与紧身裤",
    "Leon's cap and tights, in the wardrobe.": "在衣柜中添加丹帝的帽子与紧身裤。",
    "Gold studded backpack": "金色铆钉背包",
    "A gold studded backpack, in the wardrobe.": "在衣柜中添加金色铆钉背包。",
    "Four Poke Ball tees": "四件宝可梦主题 T 恤",
    "The four Poke Ball Guy and Pokemon Quest tees.": "包含精灵球、超级球、高级球的球球人 T 恤和宝可梦探险寻宝 T 恤。",
    "Poke Ball Guy tee": "精灵球球球人 T 恤",
    "Great Ball Guy tee": "超级球球球人 T 恤",
    "Ultra Ball Guy tee": "高级球球球人 T 恤",
    "Pokemon Quest tee": "宝可梦探险寻宝 T 恤",
    "Money": "金钱",
    "The card id is 1 to 65535.": "卡片 ID 必须在 1 到 65535 之间。",
    "Pick at least one outfit.": "请至少选择一套服装。",
    "The level is 0 to 100; 0 lets the game roll one.": "等级必须在 0 到 100 之间；0 表示由游戏随机决定。",
    "Add at least one item.": "请至少添加一件物品。",
    "A card carries six items at most.": "每张卡片最多携带六件物品。",
    "Battle Points are 1 to 9999.": "对战点数必须在 1 到 9999 之间。",
    "Each quantity is 1 to 999.": "每项数量必须在 1 到 999 之间。",
    "Add at least one step to the gift.": "请至少为礼物添加一个步骤。",
    "Open a gift file, or choose a preset.": "请打开礼物文件或选择预设。",
    "Choose a .pokegift file, a .wc3 file for FireRed/LeafGreen or a .wc8 file for Sword/Shield.": "请选择 .pokegift 文件、火红／叶绿的 .wc3 文件或剑／盾的 .wc8 文件。",
    "Gift file exceeds 256 KiB.": "礼物文件超过 256 KiB。",
    "Gift components must be named byte records.": "礼物组件必须是带名称的字节记录。",
    "A gift name must contain 1 to 180 characters.": "礼物名称长度必须在 1 到 180 个字符之间。",
    "A gift needs 1 to 16 named variants.": "礼物需要包含 1 到 16 个带名称的变体。",
    "Unsupported gift file format or version.": "不支持此礼物文件格式或版本。",
    "A gift game must be text.": "礼物的游戏标识必须为文本。",
    "Gift variants must be an object.": "礼物变体必须为对象。",
    "Gift options must be text, integers or tuples of integers.": "礼物选项必须为文本、整数或整数元组。",
    "Gift option lists must contain integers.": "礼物选项列表必须包含整数。",
    "Gift data and options must be objects.": "礼物数据和选项必须为对象。",
    "Console code requires gift file version 2.": "游戏机代码需要第 2 版礼物文件。",
    "Gift component bytes and hashes must be text.": "礼物组件的字节数据和哈希值必须为文本。",
    "Sword/Shield import requires --record only.": "剑／盾导入只需要 --record。",
    "Response options require --code.": "响应选项需要配合 --code 使用。",
    "--icon sets an FRLG Wonder Card's icon.": "--icon 用于设置火红／叶绿神奇卡片的图标。",
    "FRLG code import requires --code and --build only, plus response options.": "火红／叶绿代码导入需要 --code、--build 及响应选项。",
    "FRLG .wc3 import takes --wc3 alone, plus --build.": "火红／叶绿 .wc3 导入需要 --wc3 和 --build。",
    "FRLG import requires --wc3, or --card and --script.": "火红／叶绿导入需要 --wc3，或同时使用 --card 和 --script。",
    "--wc3 exports a FireRed/LeafGreen gift.": "--wc3 用于导出火红／叶绿礼物。",
})

LABELS.update({
    "Pikachu uniform": "皮卡丘队服",
    "Eevee uniform": "伊布队服",
    "Gigantamax Pikachu": "超极巨化皮卡丘",
    "A level 25 Pikachu that can Gigantamax, at the top Dynamax level.": "等级 25、极巨化等级最高且可超极巨化的皮卡丘。",
    "The Pikachu outfit, in the wardrobe.": "在衣柜中添加皮卡丘队服。",
    "The Eevee outfit, in the wardrobe.": "在衣柜中添加伊布队服。",
    "The card holds a male and a female version; the player gets their own": "卡片包含男性和女性角色对应的版本，玩家收到适合自身角色的版本。",
})


LABELS.update({'This is not a FireRed or LeafGreen save PKHeX can read.': '此存档不是 PKHeX 可读取的火红或叶绿存档。', 'A party Pokemon is not a Gen 3 Pokemon.': '队伍中有宝可梦不属于第三世代。', "A party Pokemon's checksum is invalid.": '队伍中有宝可梦的校验和无效。', 'A party holds one to six Pokemon.': '队伍必须包含一至六只宝可梦。', 'A save backup or restore sends no gift.': '备份或恢复存档时不会发送礼物。'})

LABELS.update({'Only the packed app updates itself.': '只有打包后的应用支持自动更新。', 'Move pokeldn to your Applications folder, open it from there, then update.': '请将 pokeldn 移到“应用程序”文件夹，从那里打开后再更新。', 'the download is too large': '下载文件过大', 'the release has no file for this computer or no SHA256SUMS': '发布版本没有适用于此电脑的文件或 SHA256SUMS', 'the copied app has no executable': '复制的应用中没有可执行文件', 'The Pokemon checksum is invalid.': '宝可梦数据校验和无效。', 'Nothing goes back to this game: HOME only takes from it.': '无法传回此游戏：HOME 只允许从此游戏传出。', 'An egg stays in its own game.': '蛋只能保留在当前游戏中。', 'HOME takes a FireRed or LeafGreen Pokemon only without a held item.': '从《火红／叶绿》传出到 HOME 的宝可梦不能携带道具。', 'HOME takes a FireRed or LeafGreen Pokemon only without an HM move.': '从《火红／叶绿》传出到 HOME 的宝可梦不能学有秘传招式。', 'This species or form is absent from that game.': '目标游戏中不存在此种类或形态。'})

LABELS.update({"Online trade": "在线交换", "The bank": "宝可梦银行"})

LABELS.update({
    "Tera Raids": "太晶团体战",
    "Lowest overall bulk": "最低综合耐久",
    "Lowest physical bulk": "最低物理耐久",
    "Lowest special bulk": "最低特殊耐久",
    "Weakest offense": "最低攻击能力",
    "Highest total stats": "最高能力总和",
    "Enter eight hexadecimal digits.": "请输入八位十六进制数字。",
    "scarlet": "朱", "violet": "紫",
    "paldea": "帕底亚", "kitakami": "北上乡", "blueberry": "蓝莓学园",
    "beginning": "游戏初期", "tera": "已解锁太晶团体战",
    "3star": "3 星团体战", "4star": "4 星团体战",
    "5star": "5 星团体战", "6star": "6 星团体战",
    "standard": "普通", "black": "黑色",
})
